#
# $Header: /Users/dossy/Desktop/cvs/aolserver/nsexample/Attic/Makefile,v 1.1.1.1 2000/05/02 13:48:23 kriston Exp $
#
# nsexample --
#
#      Example AOLserver module Makefile.
#

#
# Module name
#
MOD      =  nsexample.so

#
# Objects to build
#
OBJS     =  nsexample.o

#
# Header files
#
HDRS     =  

#
# Extra libraries
#
MODLIBS  =  

#
# Compiler flags
#
CFLAGS   =  


include  ../include/Makefile.module

