#!/bin/sh
# This script is invoked when installing manual entries.  It generates
# additional links to manual entries, corresponding to the procedure
# and command names described by the manual entry.  For example, the
# Tcl manual entry Hash.3 describes procedures Tcl_InitHashTable,
# Tcl_CreateHashEntry, and many more.  This script will make hard
# links so that Tcl_InitHashTable.3, Tcl_CreateHashEntry.3, and so
# on all refer to Hash.3 in the installed directory.
#
# Because of the length of command and procedure names, this mechanism
# only works on machines that support file names longer than 14 characters.
# This script checks to see if long file names are supported, and it
# doesn't make any links if they are not.
#
# The script takes one argument, which is the name of the directory
# where the manual entries have been installed.

ZIP=true
while true; do
    case $1 in
        -s | --symlinks )
            S=-s
            ;;
        -z | --compress )
            ZIP=$2
            shift
            ;;
        *) break
            ;;
    esac
    shift
done

if test $# != 1; then
    echo "Usage: mkLinks <options> dir"
    exit 1
fi

if test "x$ZIP" != "xtrue"; then
    touch TeST
    $ZIP TeST
    Z=`ls TeST* | sed 's/^[^.]*//'`
    rm -f TeST*
fi

cd $1
echo foo > xyzzyTestingAVeryLongFileName.foo
x=`echo xyzzyTe*`
echo foo > xyzzyTestingaverylongfilename.foo
y=`echo xyzzyTestingav*`
rm xyzzyTe*
if test "$x" != "xyzzyTestingAVeryLongFileName.foo"; then
    exit
fi
if test "$y" != "xyzzyTestingaverylongfilename.foo"; then
    CASEINSENSITIVEFS=1
fi

if test -r ns_addr.n; then
    rm -f ns_addr.n.*
    $ZIP ns_addr.n
    rm -f ns_addrbyhost.n ns_addrbyhost.n.* 
    rm -f ns_hostbyaddr.n ns_hostbyaddr.n.* 
    ln $S ns_addr.n$Z ns_addrbyhost.n$Z 
    ln $S ns_addr.n$Z ns_hostbyaddr.n$Z 
fi
if test -r ns_adp.n; then
    rm -f ns_adp.n.*
    $ZIP ns_adp.n
    rm -f ns_adp_abort.n ns_adp_abort.n.* 
    rm -f ns_adp_append.n ns_adp_append.n.* 
    rm -f ns_adp_argc.n ns_adp_argc.n.* 
    rm -f ns_adp_argv.n ns_adp_argv.n.* 
    rm -f ns_adp_bind_args.n ns_adp_bind_args.n.* 
    rm -f ns_adp_break.n ns_adp_break.n.* 
    rm -f ns_adp_debug.n ns_adp_debug.n.* 
    rm -f ns_adp_dir.n ns_adp_dir.n.* 
    rm -f ns_adp_dump.n ns_adp_dump.n.* 
    rm -f ns_adp_eval.n ns_adp_eval.n.* 
    rm -f ns_adp_exception.n ns_adp_exception.n.* 
    rm -f ns_adp_mime.n ns_adp_mime.n.* 
    rm -f ns_adp_mimetype.n ns_adp_mimetype.n.* 
    rm -f ns_adp_parse.n ns_adp_parse.n.* 
    rm -f ns_adp_puts.n ns_adp_puts.n.* 
    rm -f ns_adp_registeradp.n ns_adp_registeradp.n.* 
    rm -f ns_adp_registerproc.n ns_adp_registerproc.n.* 
    rm -f ns_adp_registertag.n ns_adp_registertag.n.* 
    rm -f ns_adp_return.n ns_adp_return.n.* 
    rm -f ns_adp_safeeval.n ns_adp_safeeval.n.* 
    rm -f ns_adp_stats.n ns_adp_stats.n.* 
    rm -f ns_adp_stream.n ns_adp_stream.n.* 
    rm -f ns_adp_tell.n ns_adp_tell.n.* 
    rm -f ns_adp_trunc.n ns_adp_trunc.n.* 
    rm -f ns_puts.n ns_puts.n.* 
    rm -f ns_register_adp.n ns_register_adp.n.* 
    rm -f ns_register_adptag.n ns_register_adptag.n.* 
    rm -f ns_unregister_adp.n ns_unregister_adp.n.* 
    ln $S ns_adp.n$Z ns_adp_abort.n$Z 
    ln $S ns_adp.n$Z ns_adp_append.n$Z 
    ln $S ns_adp.n$Z ns_adp_argc.n$Z 
    ln $S ns_adp.n$Z ns_adp_argv.n$Z 
    ln $S ns_adp.n$Z ns_adp_bind_args.n$Z 
    ln $S ns_adp.n$Z ns_adp_break.n$Z 
    ln $S ns_adp.n$Z ns_adp_debug.n$Z 
    ln $S ns_adp.n$Z ns_adp_dir.n$Z 
    ln $S ns_adp.n$Z ns_adp_dump.n$Z 
    ln $S ns_adp.n$Z ns_adp_eval.n$Z 
    ln $S ns_adp.n$Z ns_adp_exception.n$Z 
    ln $S ns_adp.n$Z ns_adp_mime.n$Z 
    ln $S ns_adp.n$Z ns_adp_mimetype.n$Z 
    ln $S ns_adp.n$Z ns_adp_parse.n$Z 
    ln $S ns_adp.n$Z ns_adp_puts.n$Z 
    ln $S ns_adp.n$Z ns_adp_registeradp.n$Z 
    ln $S ns_adp.n$Z ns_adp_registerproc.n$Z 
    ln $S ns_adp.n$Z ns_adp_registertag.n$Z 
    ln $S ns_adp.n$Z ns_adp_return.n$Z 
    ln $S ns_adp.n$Z ns_adp_safeeval.n$Z 
    ln $S ns_adp.n$Z ns_adp_stats.n$Z 
    ln $S ns_adp.n$Z ns_adp_stream.n$Z 
    ln $S ns_adp.n$Z ns_adp_tell.n$Z 
    ln $S ns_adp.n$Z ns_adp_trunc.n$Z 
    ln $S ns_adp.n$Z ns_puts.n$Z 
    ln $S ns_adp.n$Z ns_register_adp.n$Z 
    ln $S ns_adp.n$Z ns_register_adptag.n$Z 
    ln $S ns_adp.n$Z ns_unregister_adp.n$Z 
fi
if test -r ns_at.n; then
    rm -f ns_at.n.*
    $ZIP ns_at.n
    rm -f ns_atclose.n ns_atclose.n.* 
    rm -f ns_atexit.n ns_atexit.n.* 
    rm -f ns_atshutdown.n ns_atshutdown.n.* 
    rm -f ns_atsignal.n ns_atsignal.n.* 
    ln $S ns_at.n$Z ns_atclose.n$Z 
    ln $S ns_at.n$Z ns_atexit.n$Z 
    ln $S ns_at.n$Z ns_atshutdown.n$Z 
    ln $S ns_at.n$Z ns_atsignal.n$Z 
fi
if test -r ns_cache.n; then
    rm -f ns_cache.n.*
    $ZIP ns_cache.n
    rm -f ns_cache_flush.n ns_cache_flush.n.* 
    rm -f ns_cache_keys.n ns_cache_keys.n.* 
    rm -f ns_cache_names.n ns_cache_names.n.* 
    rm -f ns_cache_size.n ns_cache_size.n.* 
    rm -f ns_cache_stats.n ns_cache_stats.n.* 
    ln $S ns_cache.n$Z ns_cache_flush.n$Z 
    ln $S ns_cache.n$Z ns_cache_keys.n$Z 
    ln $S ns_cache.n$Z ns_cache_names.n$Z 
    ln $S ns_cache.n$Z ns_cache_size.n$Z 
    ln $S ns_cache.n$Z ns_cache_stats.n$Z 
fi
if test -r ns_chan.n; then
    rm -f ns_chan.n.*
    $ZIP ns_chan.n
fi
if test -r ns_checkurl.n; then
    rm -f ns_checkurl.n.*
    $ZIP ns_checkurl.n
fi
if test -r ns_config.n; then
    rm -f ns_config.n.*
    $ZIP ns_config.n
    rm -f ns_configsection.n ns_configsection.n.* 
    rm -f ns_configsections.n ns_configsections.n.* 
    rm -f ns_param.n ns_param.n.* 
    rm -f ns_section.n ns_section.n.* 
    ln $S ns_config.n$Z ns_configsection.n$Z 
    ln $S ns_config.n$Z ns_configsections.n$Z 
    ln $S ns_config.n$Z ns_param.n$Z 
    ln $S ns_config.n$Z ns_section.n$Z 
fi
if test -r ns_conn.n; then
    rm -f ns_conn.n.*
    $ZIP ns_conn.n
    rm -f ns_conncptofp.n ns_conncptofp.n.* 
    rm -f ns_get_multipart_formdata.n ns_get_multipart_formdata.n.* 
    rm -f ns_writecontent.n ns_writecontent.n.* 
    ln $S ns_conn.n$Z ns_conncptofp.n$Z 
    ln $S ns_conn.n$Z ns_get_multipart_formdata.n$Z 
    ln $S ns_conn.n$Z ns_writecontent.n$Z 
fi
if test -r ns_crash.n; then
    rm -f ns_crash.n.*
    $ZIP ns_crash.n
    rm -f crash.n crash.n.* 
    ln $S ns_crash.n$Z crash.n$Z 
fi
if test -r ns_crypt.n; then
    rm -f ns_crypt.n.*
    $ZIP ns_crypt.n
fi
if test -r ns_db.n; then
    rm -f ns_db.n.*
    $ZIP ns_db.n
    rm -f ns_column.n ns_column.n.* 
    rm -f ns_dbconfigpath.n ns_dbconfigpath.n.* 
    rm -f ns_dberrorcode.n ns_dberrorcode.n.* 
    rm -f ns_dberrormsg.n ns_dberrormsg.n.* 
    rm -f ns_dbreturnerror.n ns_dbreturnerror.n.* 
    rm -f ns_getcsv.n ns_getcsv.n.* 
    rm -f ns_pooldescription.n ns_pooldescription.n.* 
    rm -f ns_quotelisttolist.n ns_quotelisttolist.n.* 
    rm -f ns_table.n ns_table.n.* 
    ln $S ns_db.n$Z ns_column.n$Z 
    ln $S ns_db.n$Z ns_dbconfigpath.n$Z 
    ln $S ns_db.n$Z ns_dberrorcode.n$Z 
    ln $S ns_db.n$Z ns_dberrormsg.n$Z 
    ln $S ns_db.n$Z ns_dbreturnerror.n$Z 
    ln $S ns_db.n$Z ns_getcsv.n$Z 
    ln $S ns_db.n$Z ns_pooldescription.n$Z 
    ln $S ns_db.n$Z ns_quotelisttolist.n$Z 
    ln $S ns_db.n$Z ns_table.n$Z 
fi
if test -r ns_env.n; then
    rm -f ns_env.n.*
    $ZIP ns_env.n
    rm -f env.n env.n.* 
    ln $S ns_env.n$Z env.n$Z 
fi
if test -r ns_eval.n; then
    rm -f ns_eval.n.*
    $ZIP ns_eval.n
fi
if test -r ns_file.n; then
    rm -f ns_file.n.*
    $ZIP ns_file.n
    rm -f ns_chmod.n ns_chmod.n.* 
    rm -f ns_cp.n ns_cp.n.* 
    rm -f ns_cpfp.n ns_cpfp.n.* 
    rm -f ns_ftruncate.n ns_ftruncate.n.* 
    rm -f ns_link.n ns_link.n.* 
    rm -f ns_mkdir.n ns_mkdir.n.* 
    rm -f ns_rename.n ns_rename.n.* 
    rm -f ns_rmdir.n ns_rmdir.n.* 
    rm -f ns_symlink.n ns_symlink.n.* 
    rm -f ns_truncate.n ns_truncate.n.* 
    rm -f ns_unlink.n ns_unlink.n.* 
    ln $S ns_file.n$Z ns_chmod.n$Z 
    ln $S ns_file.n$Z ns_cp.n$Z 
    ln $S ns_file.n$Z ns_cpfp.n$Z 
    ln $S ns_file.n$Z ns_ftruncate.n$Z 
    ln $S ns_file.n$Z ns_link.n$Z 
    ln $S ns_file.n$Z ns_mkdir.n$Z 
    ln $S ns_file.n$Z ns_rename.n$Z 
    ln $S ns_file.n$Z ns_rmdir.n$Z 
    ln $S ns_file.n$Z ns_symlink.n$Z 
    ln $S ns_file.n$Z ns_truncate.n$Z 
    ln $S ns_file.n$Z ns_unlink.n$Z 
fi
if test -r ns_filter.n; then
    rm -f ns_filter.n.*
    $ZIP ns_filter.n
    rm -f ns_register_filter.n ns_register_filter.n.* 
    rm -f ns_register_trace.n ns_register_trace.n.* 
    ln $S ns_filter.n$Z ns_register_filter.n$Z 
    ln $S ns_filter.n$Z ns_register_trace.n$Z 
fi
if test -r ns_getchannels.n; then
    rm -f ns_getchannels.n.*
    $ZIP ns_getchannels.n
fi
if test -r ns_geturl.n; then
    rm -f ns_geturl.n.*
    $ZIP ns_geturl.n
fi
if test -r ns_guesstype.n; then
    rm -f ns_guesstype.n.*
    $ZIP ns_guesstype.n
fi
if test -r ns_headers.n; then
    rm -f ns_headers.n.*
    $ZIP ns_headers.n
fi
if test -r ns_html.n; then
    rm -f ns_html.n.*
    $ZIP ns_html.n
    rm -f ns_hrefs.n ns_hrefs.n.* 
    rm -f ns_quotehtml.n ns_quotehtml.n.* 
    rm -f ns_striphtml.n ns_striphtml.n.* 
    ln $S ns_html.n$Z ns_hrefs.n$Z 
    ln $S ns_html.n$Z ns_quotehtml.n$Z 
    ln $S ns_html.n$Z ns_striphtml.n$Z 
fi
if test -r ns_http.n; then
    rm -f ns_http.n.*
    $ZIP ns_http.n
fi
if test -r ns_httptime.n; then
    rm -f ns_httptime.n.*
    $ZIP ns_httptime.n
    rm -f ns_parsehttptime.n ns_parsehttptime.n.* 
    ln $S ns_httptime.n$Z ns_parsehttptime.n$Z 
fi
if test -r ns_img.n; then
    rm -f ns_img.n.*
    $ZIP ns_img.n
    rm -f ns_gifsize.n ns_gifsize.n.* 
    rm -f ns_jpegsize.n ns_jpegsize.n.* 
    ln $S ns_img.n$Z ns_gifsize.n$Z 
    ln $S ns_img.n$Z ns_jpegsize.n$Z 
fi
if test -r ns_info.n; then
    rm -f ns_info.n.*
    $ZIP ns_info.n
    rm -f ns_server.n ns_server.n.* 
    rm -f ns_stats.n ns_stats.n.* 
    ln $S ns_info.n$Z ns_server.n$Z 
    ln $S ns_info.n$Z ns_stats.n$Z 
fi
if test -r ns_init.n; then
    rm -f ns_init.n.*
    $ZIP ns_init.n
    rm -f ns_cleanup.n ns_cleanup.n.* 
    rm -f ns_ictl.n ns_ictl.n.* 
    ln $S ns_init.n$Z ns_cleanup.n$Z 
    ln $S ns_init.n$Z ns_ictl.n$Z 
fi
if test -r ns_job.n; then
    rm -f ns_job.n.*
    $ZIP ns_job.n
fi
if test -r ns_kill.n; then
    rm -f ns_kill.n.*
    $ZIP ns_kill.n
fi
if test -r ns_library.n; then
    rm -f ns_library.n.*
    $ZIP ns_library.n
fi
if test -r ns_log.n; then
    rm -f ns_log.n.*
    $ZIP ns_log.n
    rm -f ns_logctl.n ns_logctl.n.* 
    ln $S ns_log.n$Z ns_logctl.n$Z 
fi
if test -r ns_logroll.n; then
    rm -f ns_logroll.n.*
    $ZIP ns_logroll.n
fi
if test -r ns_markfordelete.n; then
    rm -f ns_markfordelete.n.*
    $ZIP ns_markfordelete.n
fi
if test -r ns_module.n; then
    rm -f ns_module.n.*
    $ZIP ns_module.n
fi
if test -r ns_modulepath.n; then
    rm -f ns_modulepath.n.*
    $ZIP ns_modulepath.n
fi
if test -r ns_normalizepath.n; then
    rm -f ns_normalizepath.n.*
    $ZIP ns_normalizepath.n
fi
if test -r ns_parseheader.n; then
    rm -f ns_parseheader.n.*
    $ZIP ns_parseheader.n
fi
if test -r ns_parsequery.n; then
    rm -f ns_parsequery.n.*
    $ZIP ns_parsequery.n
fi
if test -r ns_proc.n; then
    rm -f ns_proc.n.*
    $ZIP ns_proc.n
    rm -f ns_register_proc.n ns_register_proc.n.* 
    rm -f ns_unregister_proc.n ns_unregister_proc.n.* 
    ln $S ns_proc.n$Z ns_register_proc.n$Z 
    ln $S ns_proc.n$Z ns_unregister_proc.n$Z 
fi
if test -r ns_purgefiles.n; then
    rm -f ns_purgefiles.n.*
    $ZIP ns_purgefiles.n
fi
if test -r ns_rand.n; then
    rm -f ns_rand.n.*
    $ZIP ns_rand.n
fi
if test -r ns_requestauthorize.n; then
    rm -f ns_requestauthorize.n.*
    $ZIP ns_requestauthorize.n
fi
if test -r ns_return.n; then
    rm -f ns_return.n.*
    $ZIP ns_return.n
    rm -f ns_connsendfp.n ns_connsendfp.n.* 
    rm -f ns_respond.n ns_respond.n.* 
    rm -f ns_returnadminnotice.n ns_returnadminnotice.n.* 
    rm -f ns_returnbadrequest.n ns_returnbadrequest.n.* 
    rm -f ns_returnerror.n ns_returnerror.n.* 
    rm -f ns_returnfile.n ns_returnfile.n.* 
    rm -f ns_returnforbidden.n ns_returnforbidden.n.* 
    rm -f ns_returnfp.n ns_returnfp.n.* 
    rm -f ns_returnnotfound.n ns_returnnotfound.n.* 
    rm -f ns_returnnotice.n ns_returnnotice.n.* 
    rm -f ns_returnredirect.n ns_returnredirect.n.* 
    rm -f ns_returnunauthorized.n ns_returnunauthorized.n.* 
    rm -f ns_write.n ns_write.n.* 
    ln $S ns_return.n$Z ns_connsendfp.n$Z 
    ln $S ns_return.n$Z ns_respond.n$Z 
    ln $S ns_return.n$Z ns_returnadminnotice.n$Z 
    ln $S ns_return.n$Z ns_returnbadrequest.n$Z 
    ln $S ns_return.n$Z ns_returnerror.n$Z 
    ln $S ns_return.n$Z ns_returnfile.n$Z 
    ln $S ns_return.n$Z ns_returnforbidden.n$Z 
    ln $S ns_return.n$Z ns_returnfp.n$Z 
    ln $S ns_return.n$Z ns_returnnotfound.n$Z 
    ln $S ns_return.n$Z ns_returnnotice.n$Z 
    ln $S ns_return.n$Z ns_returnredirect.n$Z 
    ln $S ns_return.n$Z ns_returnunauthorized.n$Z 
    ln $S ns_return.n$Z ns_write.n$Z 
fi
if test -r ns_rollfile.n; then
    rm -f ns_rollfile.n.*
    $ZIP ns_rollfile.n
fi
if test -r ns_sched.n; then
    rm -f ns_sched.n.*
    $ZIP ns_sched.n
    rm -f ns_after.n ns_after.n.* 
    rm -f ns_cancel.n ns_cancel.n.* 
    rm -f ns_pause.n ns_pause.n.* 
    rm -f ns_resume.n ns_resume.n.* 
    rm -f ns_schedule_daily.n ns_schedule_daily.n.* 
    rm -f ns_schedule_proc.n ns_schedule_proc.n.* 
    rm -f ns_schedule_weekly.n ns_schedule_weekly.n.* 
    rm -f ns_unschedule_proc.n ns_unschedule_proc.n.* 
    ln $S ns_sched.n$Z ns_after.n$Z 
    ln $S ns_sched.n$Z ns_cancel.n$Z 
    ln $S ns_sched.n$Z ns_pause.n$Z 
    ln $S ns_sched.n$Z ns_resume.n$Z 
    ln $S ns_sched.n$Z ns_schedule_daily.n$Z 
    ln $S ns_sched.n$Z ns_schedule_proc.n$Z 
    ln $S ns_sched.n$Z ns_schedule_weekly.n$Z 
    ln $S ns_sched.n$Z ns_unschedule_proc.n$Z 
fi
if test -r ns_set.n; then
    rm -f ns_set.n.*
    $ZIP ns_set.n
fi
if test -r ns_share.n; then
    rm -f ns_share.n.*
    $ZIP ns_share.n
    rm -f ns_var.n ns_var.n.* 
    rm -f nsv_append.n nsv_append.n.* 
    rm -f nsv_array.n nsv_array.n.* 
    rm -f nsv_exists.n nsv_exists.n.* 
    rm -f nsv_get.n nsv_get.n.* 
    rm -f nsv_incr.n nsv_incr.n.* 
    rm -f nsv_lappend.n nsv_lappend.n.* 
    rm -f nsv_names.n nsv_names.n.* 
    rm -f nsv_set.n nsv_set.n.* 
    rm -f nsv_unset.n nsv_unset.n.* 
    ln $S ns_share.n$Z ns_var.n$Z 
    ln $S ns_share.n$Z nsv_append.n$Z 
    ln $S ns_share.n$Z nsv_array.n$Z 
    ln $S ns_share.n$Z nsv_exists.n$Z 
    ln $S ns_share.n$Z nsv_get.n$Z 
    ln $S ns_share.n$Z nsv_incr.n$Z 
    ln $S ns_share.n$Z nsv_lappend.n$Z 
    ln $S ns_share.n$Z nsv_names.n$Z 
    ln $S ns_share.n$Z nsv_set.n$Z 
    ln $S ns_share.n$Z nsv_unset.n$Z 
fi
if test -r ns_shutdown.n; then
    rm -f ns_shutdown.n.*
    $ZIP ns_shutdown.n
fi
if test -r ns_sleep.n; then
    rm -f ns_sleep.n.*
    $ZIP ns_sleep.n
fi
if test -r ns_sock.n; then
    rm -f ns_sock.n.*
    $ZIP ns_sock.n
    rm -f ns_sockaccept.n ns_sockaccept.n.* 
    rm -f ns_sockblocking.n ns_sockblocking.n.* 
    rm -f ns_sockcallback.n ns_sockcallback.n.* 
    rm -f ns_sockcheck.n ns_sockcheck.n.* 
    rm -f ns_socketpair.n ns_socketpair.n.* 
    rm -f ns_socklisten.n ns_socklisten.n.* 
    rm -f ns_socklistencallback.n ns_socklistencallback.n.* 
    rm -f ns_socknonblocking.n ns_socknonblocking.n.* 
    rm -f ns_socknread.n ns_socknread.n.* 
    rm -f ns_sockopen.n ns_sockopen.n.* 
    rm -f ns_sockselect.n ns_sockselect.n.* 
    ln $S ns_sock.n$Z ns_sockaccept.n$Z 
    ln $S ns_sock.n$Z ns_sockblocking.n$Z 
    ln $S ns_sock.n$Z ns_sockcallback.n$Z 
    ln $S ns_sock.n$Z ns_sockcheck.n$Z 
    ln $S ns_sock.n$Z ns_socketpair.n$Z 
    ln $S ns_sock.n$Z ns_socklisten.n$Z 
    ln $S ns_sock.n$Z ns_socklistencallback.n$Z 
    ln $S ns_sock.n$Z ns_socknonblocking.n$Z 
    ln $S ns_sock.n$Z ns_socknread.n$Z 
    ln $S ns_sock.n$Z ns_sockopen.n$Z 
    ln $S ns_sock.n$Z ns_sockselect.n$Z 
fi
if test -r ns_sync.n; then
    rm -f ns_sync.n.*
    $ZIP ns_sync.n
    rm -f ns_cond.n ns_cond.n.* 
    rm -f ns_critsec.n ns_critsec.n.* 
    rm -f ns_event.n ns_event.n.* 
    rm -f ns_mutex.n ns_mutex.n.* 
    rm -f ns_rwlock.n ns_rwlock.n.* 
    rm -f ns_sema.n ns_sema.n.* 
    ln $S ns_sync.n$Z ns_cond.n$Z 
    ln $S ns_sync.n$Z ns_critsec.n$Z 
    ln $S ns_sync.n$Z ns_event.n$Z 
    ln $S ns_sync.n$Z ns_mutex.n$Z 
    ln $S ns_sync.n$Z ns_rwlock.n$Z 
    ln $S ns_sync.n$Z ns_sema.n$Z 
fi
if test -r ns_thread.n; then
    rm -f ns_thread.n.*
    $ZIP ns_thread.n
fi
if test -r ns_time.n; then
    rm -f ns_time.n.*
    $ZIP ns_time.n
    rm -f ns_fmttime.n ns_fmttime.n.* 
    rm -f ns_gmtime.n ns_gmtime.n.* 
    rm -f ns_localtime.n ns_localtime.n.* 
    ln $S ns_time.n$Z ns_fmttime.n$Z 
    ln $S ns_time.n$Z ns_gmtime.n$Z 
    ln $S ns_time.n$Z ns_localtime.n$Z 
fi
if test -r ns_tmp.n; then
    rm -f ns_tmp.n.*
    $ZIP ns_tmp.n
    rm -f ns_mktemp.n ns_mktemp.n.* 
    rm -f ns_tmpnam.n ns_tmpnam.n.* 
    ln $S ns_tmp.n$Z ns_mktemp.n$Z 
    ln $S ns_tmp.n$Z ns_tmpnam.n$Z 
fi
if test -r ns_url2file.n; then
    rm -f ns_url2file.n.*
    $ZIP ns_url2file.n
fi
if test -r ns_urlencode.n; then
    rm -f ns_urlencode.n.*
    $ZIP ns_urlencode.n
    rm -f ns_urldecode.n ns_urldecode.n.* 
    ln $S ns_urlencode.n$Z ns_urldecode.n$Z 
fi
if test -r ns_uuencode.n; then
    rm -f ns_uuencode.n.*
    $ZIP ns_uuencode.n
    rm -f ns_uudecode.n ns_uudecode.n.* 
    ln $S ns_uuencode.n$Z ns_uudecode.n$Z 
fi
if test -r ns_writefp.n; then
    rm -f ns_writefp.n.*
    $ZIP ns_writefp.n
fi
if test -r Ns_Adp.3; then
    rm -f Ns_Adp.3.*
    $ZIP Ns_Adp.3
    rm -f Ns_AdpRegisterParser.3 Ns_AdpRegisterParser.3.* 
    rm -f Ns_AdpRequest.3 Ns_AdpRequest.3.* 
    ln $S Ns_Adp.3$Z Ns_AdpRegisterParser.3$Z 
    ln $S Ns_Adp.3$Z Ns_AdpRequest.3$Z 
fi
if test -r Ns_Alloc.3; then
    rm -f Ns_Alloc.3.*
    $ZIP Ns_Alloc.3
    rm -f Ns_Calloc.3 Ns_Calloc.3.* 
    rm -f Ns_Free.3 Ns_Free.3.* 
    rm -f Ns_Malloc.3 Ns_Malloc.3.* 
    rm -f Ns_Realloc.3 Ns_Realloc.3.* 
    rm -f ns_calloc.3 ns_calloc.3.* 
    rm -f ns_free.3 ns_free.3.* 
    rm -f ns_malloc.3 ns_malloc.3.* 
    rm -f ns_realloc.3 ns_realloc.3.* 
    ln $S Ns_Alloc.3$Z Ns_Calloc.3$Z 
    ln $S Ns_Alloc.3$Z Ns_Free.3$Z 
    ln $S Ns_Alloc.3$Z Ns_Malloc.3$Z 
    ln $S Ns_Alloc.3$Z Ns_Realloc.3$Z 
    ln $S Ns_Alloc.3$Z ns_calloc.3$Z 
    ln $S Ns_Alloc.3$Z ns_free.3$Z 
    ln $S Ns_Alloc.3$Z ns_malloc.3$Z 
    ln $S Ns_Alloc.3$Z ns_realloc.3$Z 
fi
if test -r Ns_Auth.3; then
    rm -f Ns_Auth.3.*
    $ZIP Ns_Auth.3
    rm -f Ns_SetRequestAuthorizeProc.3 Ns_SetRequestAuthorizeProc.3.* 
    rm -f Ns_SetUserAuthorizeProc.3 Ns_SetUserAuthorizeProc.3.* 
    ln $S Ns_Auth.3$Z Ns_SetRequestAuthorizeProc.3$Z 
    ln $S Ns_Auth.3$Z Ns_SetUserAuthorizeProc.3$Z 
fi
if test -r Ns_Cache.3; then
    rm -f Ns_Cache.3.*
    $ZIP Ns_Cache.3
    rm -f Ns_CacheBroadcast.3 Ns_CacheBroadcast.3.* 
    rm -f Ns_CacheCreate.3 Ns_CacheCreate.3.* 
    rm -f Ns_CacheCreateEntry.3 Ns_CacheCreateEntry.3.* 
    rm -f Ns_CacheCreateSz.3 Ns_CacheCreateSz.3.* 
    rm -f Ns_CacheDeleteEntry.3 Ns_CacheDeleteEntry.3.* 
    rm -f Ns_CacheDestroy.3 Ns_CacheDestroy.3.* 
    rm -f Ns_CacheFind.3 Ns_CacheFind.3.* 
    rm -f Ns_CacheFindEntry.3 Ns_CacheFindEntry.3.* 
    rm -f Ns_CacheFirstEntry.3 Ns_CacheFirstEntry.3.* 
    rm -f Ns_CacheFlush.3 Ns_CacheFlush.3.* 
    rm -f Ns_CacheFlushEntry.3 Ns_CacheFlushEntry.3.* 
    rm -f Ns_CacheFree.3 Ns_CacheFree.3.* 
    rm -f Ns_CacheGetValue.3 Ns_CacheGetValue.3.* 
    rm -f Ns_CacheKey.3 Ns_CacheKey.3.* 
    rm -f Ns_CacheLock.3 Ns_CacheLock.3.* 
    rm -f Ns_CacheMalloc.3 Ns_CacheMalloc.3.* 
    rm -f Ns_CacheName.3 Ns_CacheName.3.* 
    rm -f Ns_CacheNextEntry.3 Ns_CacheNextEntry.3.* 
    rm -f Ns_CacheSetValue.3 Ns_CacheSetValue.3.* 
    rm -f Ns_CacheSetValueSz.3 Ns_CacheSetValueSz.3.* 
    rm -f Ns_CacheSignal.3 Ns_CacheSignal.3.* 
    rm -f Ns_CacheTimedWait.3 Ns_CacheTimedWait.3.* 
    rm -f Ns_CacheUnlock.3 Ns_CacheUnlock.3.* 
    rm -f Ns_CacheUnsetValue.3 Ns_CacheUnsetValue.3.* 
    rm -f Ns_CacheWait.3 Ns_CacheWait.3.* 
    ln $S Ns_Cache.3$Z Ns_CacheBroadcast.3$Z 
    ln $S Ns_Cache.3$Z Ns_CacheCreate.3$Z 
    ln $S Ns_Cache.3$Z Ns_CacheCreateEntry.3$Z 
    ln $S Ns_Cache.3$Z Ns_CacheCreateSz.3$Z 
    ln $S Ns_Cache.3$Z Ns_CacheDeleteEntry.3$Z 
    ln $S Ns_Cache.3$Z Ns_CacheDestroy.3$Z 
    ln $S Ns_Cache.3$Z Ns_CacheFind.3$Z 
    ln $S Ns_Cache.3$Z Ns_CacheFindEntry.3$Z 
    ln $S Ns_Cache.3$Z Ns_CacheFirstEntry.3$Z 
    ln $S Ns_Cache.3$Z Ns_CacheFlush.3$Z 
    ln $S Ns_Cache.3$Z Ns_CacheFlushEntry.3$Z 
    ln $S Ns_Cache.3$Z Ns_CacheFree.3$Z 
    ln $S Ns_Cache.3$Z Ns_CacheGetValue.3$Z 
    ln $S Ns_Cache.3$Z Ns_CacheKey.3$Z 
    ln $S Ns_Cache.3$Z Ns_CacheLock.3$Z 
    ln $S Ns_Cache.3$Z Ns_CacheMalloc.3$Z 
    ln $S Ns_Cache.3$Z Ns_CacheName.3$Z 
    ln $S Ns_Cache.3$Z Ns_CacheNextEntry.3$Z 
    ln $S Ns_Cache.3$Z Ns_CacheSetValue.3$Z 
    ln $S Ns_Cache.3$Z Ns_CacheSetValueSz.3$Z 
    ln $S Ns_Cache.3$Z Ns_CacheSignal.3$Z 
    ln $S Ns_Cache.3$Z Ns_CacheTimedWait.3$Z 
    ln $S Ns_Cache.3$Z Ns_CacheUnlock.3$Z 
    ln $S Ns_Cache.3$Z Ns_CacheUnsetValue.3$Z 
    ln $S Ns_Cache.3$Z Ns_CacheWait.3$Z 
fi
if test -r Ns_Cls.3; then
    rm -f Ns_Cls.3.*
    $ZIP Ns_Cls.3
    rm -f Ns_ClsAlloc.3 Ns_ClsAlloc.3.* 
    rm -f Ns_ClsGet.3 Ns_ClsGet.3.* 
    rm -f Ns_ClsSet.3 Ns_ClsSet.3.* 
    ln $S Ns_Cls.3$Z Ns_ClsAlloc.3$Z 
    ln $S Ns_Cls.3$Z Ns_ClsGet.3$Z 
    ln $S Ns_Cls.3$Z Ns_ClsSet.3$Z 
fi
if test -r Ns_Cond.3; then
    rm -f Ns_Cond.3.*
    $ZIP Ns_Cond.3
    rm -f Ns_CondBroadcast.3 Ns_CondBroadcast.3.* 
    rm -f Ns_CondDestroy.3 Ns_CondDestroy.3.* 
    rm -f Ns_CondInit.3 Ns_CondInit.3.* 
    rm -f Ns_CondSignal.3 Ns_CondSignal.3.* 
    rm -f Ns_CondTimedWait.3 Ns_CondTimedWait.3.* 
    rm -f Ns_CondWait.3 Ns_CondWait.3.* 
    ln $S Ns_Cond.3$Z Ns_CondBroadcast.3$Z 
    ln $S Ns_Cond.3$Z Ns_CondDestroy.3$Z 
    ln $S Ns_Cond.3$Z Ns_CondInit.3$Z 
    ln $S Ns_Cond.3$Z Ns_CondSignal.3$Z 
    ln $S Ns_Cond.3$Z Ns_CondTimedWait.3$Z 
    ln $S Ns_Cond.3$Z Ns_CondWait.3$Z 
fi
if test -r Ns_Config.3; then
    rm -f Ns_Config.3.*
    $ZIP Ns_Config.3
    rm -f Ns_ConfigGetBool.3 Ns_ConfigGetBool.3.* 
    rm -f Ns_ConfigGetInt.3 Ns_ConfigGetInt.3.* 
    rm -f Ns_ConfigGetInt64.3 Ns_ConfigGetInt64.3.* 
    rm -f Ns_ConfigGetPath.3 Ns_ConfigGetPath.3.* 
    rm -f Ns_ConfigGetSection.3 Ns_ConfigGetSection.3.* 
    rm -f Ns_ConfigGetSections.3 Ns_ConfigGetSections.3.* 
    rm -f Ns_ConfigGetValue.3 Ns_ConfigGetValue.3.* 
    rm -f Ns_ConfigGetValueExact.3 Ns_ConfigGetValueExact.3.* 
    ln $S Ns_Config.3$Z Ns_ConfigGetBool.3$Z 
    ln $S Ns_Config.3$Z Ns_ConfigGetInt.3$Z 
    ln $S Ns_Config.3$Z Ns_ConfigGetInt64.3$Z 
    ln $S Ns_Config.3$Z Ns_ConfigGetPath.3$Z 
    ln $S Ns_Config.3$Z Ns_ConfigGetSection.3$Z 
    ln $S Ns_Config.3$Z Ns_ConfigGetSections.3$Z 
    ln $S Ns_Config.3$Z Ns_ConfigGetValue.3$Z 
    ln $S Ns_Config.3$Z Ns_ConfigGetValueExact.3$Z 
fi
if test -r Ns_Conn.3; then
    rm -f Ns_Conn.3.*
    $ZIP Ns_Conn.3
    rm -f Ns_ConnAuthPasswd.3 Ns_ConnAuthPasswd.3.* 
    rm -f Ns_ConnAuthUser.3 Ns_ConnAuthUser.3.* 
    rm -f Ns_ConnContent.3 Ns_ConnContent.3.* 
    rm -f Ns_ConnContentLength.3 Ns_ConnContentLength.3.* 
    rm -f Ns_ConnGetQuery.3 Ns_ConnGetQuery.3.* 
    rm -f Ns_ConnHeaders.3 Ns_ConnHeaders.3.* 
    rm -f Ns_ConnHost.3 Ns_ConnHost.3.* 
    rm -f Ns_ConnId.3 Ns_ConnId.3.* 
    rm -f Ns_ConnInit.3 Ns_ConnInit.3.* 
    rm -f Ns_ConnLocation.3 Ns_ConnLocation.3.* 
    rm -f Ns_ConnModifiedSince.3 Ns_ConnModifiedSince.3.* 
    rm -f Ns_ConnOutputHeaders.3 Ns_ConnOutputHeaders.3.* 
    rm -f Ns_ConnPeer.3 Ns_ConnPeer.3.* 
    rm -f Ns_ConnPeerPort.3 Ns_ConnPeerPort.3.* 
    rm -f Ns_ConnPort.3 Ns_ConnPort.3.* 
    rm -f Ns_ConnReplaceHeaders.3 Ns_ConnReplaceHeaders.3.* 
    rm -f Ns_ConnResetReturn.3 Ns_ConnResetReturn.3.* 
    rm -f Ns_ConnResponseLength.3 Ns_ConnResponseLength.3.* 
    rm -f Ns_ConnResponseStatus.3 Ns_ConnResponseStatus.3.* 
    rm -f Ns_ConnServer.3 Ns_ConnServer.3.* 
    rm -f Ns_ConnSock.3 Ns_ConnSock.3.* 
    rm -f Ns_GetConn.3 Ns_GetConn.3.* 
    ln $S Ns_Conn.3$Z Ns_ConnAuthPasswd.3$Z 
    ln $S Ns_Conn.3$Z Ns_ConnAuthUser.3$Z 
    ln $S Ns_Conn.3$Z Ns_ConnContent.3$Z 
    ln $S Ns_Conn.3$Z Ns_ConnContentLength.3$Z 
    ln $S Ns_Conn.3$Z Ns_ConnGetQuery.3$Z 
    ln $S Ns_Conn.3$Z Ns_ConnHeaders.3$Z 
    ln $S Ns_Conn.3$Z Ns_ConnHost.3$Z 
    ln $S Ns_Conn.3$Z Ns_ConnId.3$Z 
    ln $S Ns_Conn.3$Z Ns_ConnInit.3$Z 
    ln $S Ns_Conn.3$Z Ns_ConnLocation.3$Z 
    ln $S Ns_Conn.3$Z Ns_ConnModifiedSince.3$Z 
    ln $S Ns_Conn.3$Z Ns_ConnOutputHeaders.3$Z 
    ln $S Ns_Conn.3$Z Ns_ConnPeer.3$Z 
    ln $S Ns_Conn.3$Z Ns_ConnPeerPort.3$Z 
    ln $S Ns_Conn.3$Z Ns_ConnPort.3$Z 
    ln $S Ns_Conn.3$Z Ns_ConnReplaceHeaders.3$Z 
    ln $S Ns_Conn.3$Z Ns_ConnResetReturn.3$Z 
    ln $S Ns_Conn.3$Z Ns_ConnResponseLength.3$Z 
    ln $S Ns_Conn.3$Z Ns_ConnResponseStatus.3$Z 
    ln $S Ns_Conn.3$Z Ns_ConnServer.3$Z 
    ln $S Ns_Conn.3$Z Ns_ConnSock.3$Z 
    ln $S Ns_Conn.3$Z Ns_GetConn.3$Z 
fi
if test -r Ns_ConnCopy.3; then
    rm -f Ns_ConnCopy.3.*
    $ZIP Ns_ConnCopy.3
    rm -f Ns_ConnCopyToChannel.3 Ns_ConnCopyToChannel.3.* 
    rm -f Ns_ConnCopyToDString.3 Ns_ConnCopyToDString.3.* 
    rm -f Ns_ConnCopyToFd.3 Ns_ConnCopyToFd.3.* 
    rm -f Ns_ConnCopyToFile.3 Ns_ConnCopyToFile.3.* 
    ln $S Ns_ConnCopy.3$Z Ns_ConnCopyToChannel.3$Z 
    ln $S Ns_ConnCopy.3$Z Ns_ConnCopyToDString.3$Z 
    ln $S Ns_ConnCopy.3$Z Ns_ConnCopyToFd.3$Z 
    ln $S Ns_ConnCopy.3$Z Ns_ConnCopyToFile.3$Z 
fi
if test -r Ns_ConnDriver.3; then
    rm -f Ns_ConnDriver.3.*
    $ZIP Ns_ConnDriver.3
    rm -f Ns_ConnDriverContext.3 Ns_ConnDriverContext.3.* 
    rm -f Ns_ConnDriverName.3 Ns_ConnDriverName.3.* 
    ln $S Ns_ConnDriver.3$Z Ns_ConnDriverContext.3$Z 
    ln $S Ns_ConnDriver.3$Z Ns_ConnDriverName.3$Z 
fi
if test -r Ns_ConnHeaders.3; then
    rm -f Ns_ConnHeaders.3.*
    $ZIP Ns_ConnHeaders.3
    rm -f Ns_ConnCondSetHeaders.3 Ns_ConnCondSetHeaders.3.* 
    rm -f Ns_ConnConstructHeaders.3 Ns_ConnConstructHeaders.3.* 
    rm -f Ns_ConnFlushHeaders.3 Ns_ConnFlushHeaders.3.* 
    rm -f Ns_ConnPrintfHeader.3 Ns_ConnPrintfHeader.3.* 
    rm -f Ns_ConnQueueHeaders.3 Ns_ConnQueueHeaders.3.* 
    rm -f Ns_ConnSetExpiresHeader.3 Ns_ConnSetExpiresHeader.3.* 
    rm -f Ns_ConnSetHeaders.3 Ns_ConnSetHeaders.3.* 
    rm -f Ns_ConnSetLastModifiedHeader.3 Ns_ConnSetLastModifiedHeader.3.* 
    rm -f Ns_ConnSetLengthHeader.3 Ns_ConnSetLengthHeader.3.* 
    rm -f Ns_ConnSetRequiredHeaders.3 Ns_ConnSetRequiredHeaders.3.* 
    rm -f Ns_ConnSetTypeHeader.3 Ns_ConnSetTypeHeader.3.* 
    ln $S Ns_ConnHeaders.3$Z Ns_ConnCondSetHeaders.3$Z 
    ln $S Ns_ConnHeaders.3$Z Ns_ConnConstructHeaders.3$Z 
    ln $S Ns_ConnHeaders.3$Z Ns_ConnFlushHeaders.3$Z 
    ln $S Ns_ConnHeaders.3$Z Ns_ConnPrintfHeader.3$Z 
    ln $S Ns_ConnHeaders.3$Z Ns_ConnQueueHeaders.3$Z 
    ln $S Ns_ConnHeaders.3$Z Ns_ConnSetExpiresHeader.3$Z 
    ln $S Ns_ConnHeaders.3$Z Ns_ConnSetHeaders.3$Z 
    ln $S Ns_ConnHeaders.3$Z Ns_ConnSetLastModifiedHeader.3$Z 
    ln $S Ns_ConnHeaders.3$Z Ns_ConnSetLengthHeader.3$Z 
    ln $S Ns_ConnHeaders.3$Z Ns_ConnSetRequiredHeaders.3$Z 
    ln $S Ns_ConnHeaders.3$Z Ns_ConnSetTypeHeader.3$Z 
fi
if test -r Ns_ConnRead.3; then
    rm -f Ns_ConnRead.3.*
    $ZIP Ns_ConnRead.3
    rm -f Ns_ConnGets.3 Ns_ConnGets.3.* 
    rm -f Ns_ConnReadHeaders.3 Ns_ConnReadHeaders.3.* 
    rm -f Ns_ConnReadLine.3 Ns_ConnReadLine.3.* 
    ln $S Ns_ConnRead.3$Z Ns_ConnGets.3$Z 
    ln $S Ns_ConnRead.3$Z Ns_ConnReadHeaders.3$Z 
    ln $S Ns_ConnRead.3$Z Ns_ConnReadLine.3$Z 
fi
if test -r Ns_ConnRequest.3; then
    rm -f Ns_ConnRequest.3.*
    $ZIP Ns_ConnRequest.3
    rm -f Ns_AuthorizeRequest.3 Ns_AuthorizeRequest.3.* 
    rm -f Ns_AuthorizeUser.3 Ns_AuthorizeUser.3.* 
    rm -f Ns_ConnRunRequest.3 Ns_ConnRunRequest.3.* 
    rm -f Ns_GetRequest.3 Ns_GetRequest.3.* 
    rm -f Ns_QueueConn.3 Ns_QueueConn.3.* 
    rm -f Ns_RegisterProxyRequest.3 Ns_RegisterProxyRequest.3.* 
    rm -f Ns_RegisterRequest.3 Ns_RegisterRequest.3.* 
    rm -f Ns_UnRegisterProxyRequest.3 Ns_UnRegisterProxyRequest.3.* 
    rm -f Ns_UnRegisterRequest.3 Ns_UnRegisterRequest.3.* 
    ln $S Ns_ConnRequest.3$Z Ns_AuthorizeRequest.3$Z 
    ln $S Ns_ConnRequest.3$Z Ns_AuthorizeUser.3$Z 
    ln $S Ns_ConnRequest.3$Z Ns_ConnRunRequest.3$Z 
    ln $S Ns_ConnRequest.3$Z Ns_GetRequest.3$Z 
    ln $S Ns_ConnRequest.3$Z Ns_QueueConn.3$Z 
    ln $S Ns_ConnRequest.3$Z Ns_RegisterProxyRequest.3$Z 
    ln $S Ns_ConnRequest.3$Z Ns_RegisterRequest.3$Z 
    ln $S Ns_ConnRequest.3$Z Ns_UnRegisterProxyRequest.3$Z 
    ln $S Ns_ConnRequest.3$Z Ns_UnRegisterRequest.3$Z 
fi
if test -r Ns_ConnReturn.3; then
    rm -f Ns_ConnReturn.3.*
    $ZIP Ns_ConnReturn.3
    rm -f Ns_ConnRedirect.3 Ns_ConnRedirect.3.* 
    rm -f Ns_ConnReturnAdminNotice.3 Ns_ConnReturnAdminNotice.3.* 
    rm -f Ns_ConnReturnBadRequest.3 Ns_ConnReturnBadRequest.3.* 
    rm -f Ns_ConnReturnData.3 Ns_ConnReturnData.3.* 
    rm -f Ns_ConnReturnFile.3 Ns_ConnReturnFile.3.* 
    rm -f Ns_ConnReturnForbidden.3 Ns_ConnReturnForbidden.3.* 
    rm -f Ns_ConnReturnHtml.3 Ns_ConnReturnHtml.3.* 
    rm -f Ns_ConnReturnInternalError.3 Ns_ConnReturnInternalError.3.* 
    rm -f Ns_ConnReturnNoResponse.3 Ns_ConnReturnNoResponse.3.* 
    rm -f Ns_ConnReturnNotFound.3 Ns_ConnReturnNotFound.3.* 
    rm -f Ns_ConnReturnNotImplemented.3 Ns_ConnReturnNotImplemented.3.* 
    rm -f Ns_ConnReturnNotModified.3 Ns_ConnReturnNotModified.3.* 
    rm -f Ns_ConnReturnNotice.3 Ns_ConnReturnNotice.3.* 
    rm -f Ns_ConnReturnOk.3 Ns_ConnReturnOk.3.* 
    rm -f Ns_ConnReturnOpenChannel.3 Ns_ConnReturnOpenChannel.3.* 
    rm -f Ns_ConnReturnOpenFd.3 Ns_ConnReturnOpenFd.3.* 
    rm -f Ns_ConnReturnOpenFile.3 Ns_ConnReturnOpenFile.3.* 
    rm -f Ns_ConnReturnRedirect.3 Ns_ConnReturnRedirect.3.* 
    rm -f Ns_ConnReturnStatus.3 Ns_ConnReturnStatus.3.* 
    rm -f Ns_ConnReturnUnauthorized.3 Ns_ConnReturnUnauthorized.3.* 
    rm -f Ns_RegisterReturn.3 Ns_RegisterReturn.3.* 
    ln $S Ns_ConnReturn.3$Z Ns_ConnRedirect.3$Z 
    ln $S Ns_ConnReturn.3$Z Ns_ConnReturnAdminNotice.3$Z 
    ln $S Ns_ConnReturn.3$Z Ns_ConnReturnBadRequest.3$Z 
    ln $S Ns_ConnReturn.3$Z Ns_ConnReturnData.3$Z 
    ln $S Ns_ConnReturn.3$Z Ns_ConnReturnFile.3$Z 
    ln $S Ns_ConnReturn.3$Z Ns_ConnReturnForbidden.3$Z 
    ln $S Ns_ConnReturn.3$Z Ns_ConnReturnHtml.3$Z 
    ln $S Ns_ConnReturn.3$Z Ns_ConnReturnInternalError.3$Z 
    ln $S Ns_ConnReturn.3$Z Ns_ConnReturnNoResponse.3$Z 
    ln $S Ns_ConnReturn.3$Z Ns_ConnReturnNotFound.3$Z 
    ln $S Ns_ConnReturn.3$Z Ns_ConnReturnNotImplemented.3$Z 
    ln $S Ns_ConnReturn.3$Z Ns_ConnReturnNotModified.3$Z 
    ln $S Ns_ConnReturn.3$Z Ns_ConnReturnNotice.3$Z 
    ln $S Ns_ConnReturn.3$Z Ns_ConnReturnOk.3$Z 
    ln $S Ns_ConnReturn.3$Z Ns_ConnReturnOpenChannel.3$Z 
    ln $S Ns_ConnReturn.3$Z Ns_ConnReturnOpenFd.3$Z 
    ln $S Ns_ConnReturn.3$Z Ns_ConnReturnOpenFile.3$Z 
    ln $S Ns_ConnReturn.3$Z Ns_ConnReturnRedirect.3$Z 
    ln $S Ns_ConnReturn.3$Z Ns_ConnReturnStatus.3$Z 
    ln $S Ns_ConnReturn.3$Z Ns_ConnReturnUnauthorized.3$Z 
    ln $S Ns_ConnReturn.3$Z Ns_RegisterReturn.3$Z 
fi
if test -r Ns_ConnSend.3; then
    rm -f Ns_ConnSend.3.*
    $ZIP Ns_ConnSend.3
    rm -f Ns_ConnSendChannel.3 Ns_ConnSendChannel.3.* 
    rm -f Ns_ConnSendDString.3 Ns_ConnSendDString.3.* 
    rm -f Ns_ConnSendFd.3 Ns_ConnSendFd.3.* 
    rm -f Ns_ConnSendFp.3 Ns_ConnSendFp.3.* 
    ln $S Ns_ConnSend.3$Z Ns_ConnSendChannel.3$Z 
    ln $S Ns_ConnSend.3$Z Ns_ConnSendDString.3$Z 
    ln $S Ns_ConnSend.3$Z Ns_ConnSendFd.3$Z 
    ln $S Ns_ConnSend.3$Z Ns_ConnSendFp.3$Z 
fi
if test -r Ns_ConnWrite.3; then
    rm -f Ns_ConnWrite.3.*
    $ZIP Ns_ConnWrite.3
    rm -f Ns_ConnClose.3 Ns_ConnClose.3.* 
    rm -f Ns_ConnContentSent.3 Ns_ConnContentSent.3.* 
    rm -f Ns_ConnFlushContent.3 Ns_ConnFlushContent.3.* 
    rm -f Ns_ConnPuts.3 Ns_ConnPuts.3.* 
    rm -f Ns_ConnSend.3 Ns_ConnSend.3.* 
    rm -f Ns_WriteConn.3 Ns_WriteConn.3.* 
    ln $S Ns_ConnWrite.3$Z Ns_ConnClose.3$Z 
    ln $S Ns_ConnWrite.3$Z Ns_ConnContentSent.3$Z 
    ln $S Ns_ConnWrite.3$Z Ns_ConnFlushContent.3$Z 
    ln $S Ns_ConnWrite.3$Z Ns_ConnPuts.3$Z 
    ln $S Ns_ConnWrite.3$Z Ns_ConnSend.3$Z 
    ln $S Ns_ConnWrite.3$Z Ns_WriteConn.3$Z 
fi
if test -r Ns_CritSec.3; then
    rm -f Ns_CritSec.3.*
    $ZIP Ns_CritSec.3
    rm -f Ns_CsDestroy.3 Ns_CsDestroy.3.* 
    rm -f Ns_CsEnter.3 Ns_CsEnter.3.* 
    rm -f Ns_CsInit.3 Ns_CsInit.3.* 
    rm -f Ns_CsLeave.3 Ns_CsLeave.3.* 
    ln $S Ns_CritSec.3$Z Ns_CsDestroy.3$Z 
    ln $S Ns_CritSec.3$Z Ns_CsEnter.3$Z 
    ln $S Ns_CritSec.3$Z Ns_CsInit.3$Z 
    ln $S Ns_CritSec.3$Z Ns_CsLeave.3$Z 
fi
if test -r Ns_DString.3; then
    rm -f Ns_DString.3.*
    $ZIP Ns_DString.3
    rm -f Ns_DStringAppend.3 Ns_DStringAppend.3.* 
    rm -f Ns_DStringAppendArg.3 Ns_DStringAppendArg.3.* 
    rm -f Ns_DStringAppendArgv.3 Ns_DStringAppendArgv.3.* 
    rm -f Ns_DStringAppendElement.3 Ns_DStringAppendElement.3.* 
    rm -f Ns_DStringExport.3 Ns_DStringExport.3.* 
    rm -f Ns_DStringFree.3 Ns_DStringFree.3.* 
    rm -f Ns_DStringInit.3 Ns_DStringInit.3.* 
    rm -f Ns_DStringLength.3 Ns_DStringLength.3.* 
    rm -f Ns_DStringNAppend.3 Ns_DStringNAppend.3.* 
    rm -f Ns_DStringPop.3 Ns_DStringPop.3.* 
    rm -f Ns_DStringPrintf.3 Ns_DStringPrintf.3.* 
    rm -f Ns_DStringPush.3 Ns_DStringPush.3.* 
    rm -f Ns_DStringSetLength.3 Ns_DStringSetLength.3.* 
    rm -f Ns_DStringTrunc.3 Ns_DStringTrunc.3.* 
    rm -f Ns_DStringVPrintf.3 Ns_DStringVPrintf.3.* 
    rm -f Ns_DStringValue.3 Ns_DStringValue.3.* 
    rm -f Ns_DStringVarAppend.3 Ns_DStringVarAppend.3.* 
    ln $S Ns_DString.3$Z Ns_DStringAppend.3$Z 
    ln $S Ns_DString.3$Z Ns_DStringAppendArg.3$Z 
    ln $S Ns_DString.3$Z Ns_DStringAppendArgv.3$Z 
    ln $S Ns_DString.3$Z Ns_DStringAppendElement.3$Z 
    ln $S Ns_DString.3$Z Ns_DStringExport.3$Z 
    ln $S Ns_DString.3$Z Ns_DStringFree.3$Z 
    ln $S Ns_DString.3$Z Ns_DStringInit.3$Z 
    ln $S Ns_DString.3$Z Ns_DStringLength.3$Z 
    ln $S Ns_DString.3$Z Ns_DStringNAppend.3$Z 
    ln $S Ns_DString.3$Z Ns_DStringPop.3$Z 
    ln $S Ns_DString.3$Z Ns_DStringPrintf.3$Z 
    ln $S Ns_DString.3$Z Ns_DStringPush.3$Z 
    ln $S Ns_DString.3$Z Ns_DStringSetLength.3$Z 
    ln $S Ns_DString.3$Z Ns_DStringTrunc.3$Z 
    ln $S Ns_DString.3$Z Ns_DStringVPrintf.3$Z 
    ln $S Ns_DString.3$Z Ns_DStringValue.3$Z 
    ln $S Ns_DString.3$Z Ns_DStringVarAppend.3$Z 
fi
if test -r Ns_Db.3; then
    rm -f Ns_Db.3.*
    $ZIP Ns_Db.3
    rm -f Ns_Db0or1Row.3 Ns_Db0or1Row.3.* 
    rm -f Ns_Db1Row.3 Ns_Db1Row.3.* 
    rm -f Ns_DbBindRow.3 Ns_DbBindRow.3.* 
    rm -f Ns_DbCancel.3 Ns_DbCancel.3.* 
    rm -f Ns_DbDML.3 Ns_DbDML.3.* 
    rm -f Ns_DbExec.3 Ns_DbExec.3.* 
    rm -f Ns_DbFlush.3 Ns_DbFlush.3.* 
    rm -f Ns_DbGetRow.3 Ns_DbGetRow.3.* 
    rm -f Ns_DbResetHandle.3 Ns_DbResetHandle.3.* 
    rm -f Ns_DbSelect.3 Ns_DbSelect.3.* 
    rm -f Ns_DbSetException.3 Ns_DbSetException.3.* 
    ln $S Ns_Db.3$Z Ns_Db0or1Row.3$Z 
    ln $S Ns_Db.3$Z Ns_Db1Row.3$Z 
    ln $S Ns_Db.3$Z Ns_DbBindRow.3$Z 
    ln $S Ns_Db.3$Z Ns_DbCancel.3$Z 
    ln $S Ns_Db.3$Z Ns_DbDML.3$Z 
    ln $S Ns_Db.3$Z Ns_DbExec.3$Z 
    ln $S Ns_Db.3$Z Ns_DbFlush.3$Z 
    ln $S Ns_Db.3$Z Ns_DbGetRow.3$Z 
    ln $S Ns_Db.3$Z Ns_DbResetHandle.3$Z 
    ln $S Ns_Db.3$Z Ns_DbSelect.3$Z 
    ln $S Ns_Db.3$Z Ns_DbSetException.3$Z 
fi
if test -r Ns_DbDriver.3; then
    rm -f Ns_DbDriver.3.*
    $ZIP Ns_DbDriver.3
    rm -f Ns_DbDriverDbType.3 Ns_DbDriverDbType.3.* 
    rm -f Ns_DbDriverName.3 Ns_DbDriverName.3.* 
    rm -f Ns_DbRegisterDriver.3 Ns_DbRegisterDriver.3.* 
    ln $S Ns_DbDriver.3$Z Ns_DbDriverDbType.3$Z 
    ln $S Ns_DbDriver.3$Z Ns_DbDriverName.3$Z 
    ln $S Ns_DbDriver.3$Z Ns_DbRegisterDriver.3$Z 
fi
if test -r Ns_DbPool.3; then
    rm -f Ns_DbPool.3.*
    $ZIP Ns_DbPool.3
    rm -f Ns_DbBouncePool.3 Ns_DbBouncePool.3.* 
    rm -f Ns_DbPoolAllowable.3 Ns_DbPoolAllowable.3.* 
    rm -f Ns_DbPoolDefault.3 Ns_DbPoolDefault.3.* 
    rm -f Ns_DbPoolDescription.3 Ns_DbPoolDescription.3.* 
    rm -f Ns_DbPoolGetHandle.3 Ns_DbPoolGetHandle.3.* 
    rm -f Ns_DbPoolGetMultipleHandles.3 Ns_DbPoolGetMultipleHandles.3.* 
    rm -f Ns_DbPoolList.3 Ns_DbPoolList.3.* 
    rm -f Ns_DbPoolPutHandle.3 Ns_DbPoolPutHandle.3.* 
    rm -f Ns_DbPoolTimedGetHandle.3 Ns_DbPoolTimedGetHandle.3.* 
    rm -f Ns_DbPoolTimedGetMultipleHandles.3 Ns_DbPoolTimedGetMultipleHandles.3.* 
    ln $S Ns_DbPool.3$Z Ns_DbBouncePool.3$Z 
    ln $S Ns_DbPool.3$Z Ns_DbPoolAllowable.3$Z 
    ln $S Ns_DbPool.3$Z Ns_DbPoolDefault.3$Z 
    ln $S Ns_DbPool.3$Z Ns_DbPoolDescription.3$Z 
    ln $S Ns_DbPool.3$Z Ns_DbPoolGetHandle.3$Z 
    ln $S Ns_DbPool.3$Z Ns_DbPoolGetMultipleHandles.3$Z 
    ln $S Ns_DbPool.3$Z Ns_DbPoolList.3$Z 
    ln $S Ns_DbPool.3$Z Ns_DbPoolPutHandle.3$Z 
    ln $S Ns_DbPool.3$Z Ns_DbPoolTimedGetHandle.3$Z 
    ln $S Ns_DbPool.3$Z Ns_DbPoolTimedGetMultipleHandles.3$Z 
fi
if test -r Ns_DbSp.3; then
    rm -f Ns_DbSp.3.*
    $ZIP Ns_DbSp.3
    rm -f Ns_DbSpExec.3 Ns_DbSpExec.3.* 
    rm -f Ns_DbSpGetParams.3 Ns_DbSpGetParams.3.* 
    rm -f Ns_DbSpReturnCode.3 Ns_DbSpReturnCode.3.* 
    rm -f Ns_DbSpSetParam.3 Ns_DbSpSetParam.3.* 
    rm -f Ns_DbSpStart.3 Ns_DbSpStart.3.* 
    ln $S Ns_DbSp.3$Z Ns_DbSpExec.3$Z 
    ln $S Ns_DbSp.3$Z Ns_DbSpGetParams.3$Z 
    ln $S Ns_DbSp.3$Z Ns_DbSpReturnCode.3$Z 
    ln $S Ns_DbSp.3$Z Ns_DbSpSetParam.3$Z 
    ln $S Ns_DbSp.3$Z Ns_DbSpStart.3$Z 
fi
if test -r Ns_DbUtil.3; then
    rm -f Ns_DbUtil.3.*
    $ZIP Ns_DbUtil.3
    rm -f Ns_DbInterpretSqlFile.3 Ns_DbInterpretSqlFile.3.* 
    rm -f Ns_DbQuoteValue.3 Ns_DbQuoteValue.3.* 
    ln $S Ns_DbUtil.3$Z Ns_DbInterpretSqlFile.3$Z 
    ln $S Ns_DbUtil.3$Z Ns_DbQuoteValue.3$Z 
fi
if test -r Ns_Driver.3; then
    rm -f Ns_Driver.3.*
    $ZIP Ns_Driver.3
    rm -f Ns_DriverInit.3 Ns_DriverInit.3.* 
    rm -f Ns_GetDriverContext.3 Ns_GetDriverContext.3.* 
    rm -f Ns_RegisterDriver.3 Ns_RegisterDriver.3.* 
    ln $S Ns_Driver.3$Z Ns_DriverInit.3$Z 
    ln $S Ns_Driver.3$Z Ns_GetDriverContext.3$Z 
    ln $S Ns_Driver.3$Z Ns_RegisterDriver.3$Z 
fi
if test -r Ns_Encoding.3; then
    rm -f Ns_Encoding.3.*
    $ZIP Ns_Encoding.3
    rm -f Ns_ConnGetEncoding.3 Ns_ConnGetEncoding.3.* 
    rm -f Ns_ConnSetEncoding.3 Ns_ConnSetEncoding.3.* 
    rm -f Ns_GetCharsetEncoding.3 Ns_GetCharsetEncoding.3.* 
    rm -f Ns_GetEncoding.3 Ns_GetEncoding.3.* 
    rm -f Ns_GetFileEncoding.3 Ns_GetFileEncoding.3.* 
    rm -f Ns_GetTypeEncoding.3 Ns_GetTypeEncoding.3.* 
    ln $S Ns_Encoding.3$Z Ns_ConnGetEncoding.3$Z 
    ln $S Ns_Encoding.3$Z Ns_ConnSetEncoding.3$Z 
    ln $S Ns_Encoding.3$Z Ns_GetCharsetEncoding.3$Z 
    ln $S Ns_Encoding.3$Z Ns_GetEncoding.3$Z 
    ln $S Ns_Encoding.3$Z Ns_GetFileEncoding.3$Z 
    ln $S Ns_Encoding.3$Z Ns_GetTypeEncoding.3$Z 
fi
if test -r Ns_Encrypt.3; then
    rm -f Ns_Encrypt.3.*
    $ZIP Ns_Encrypt.3
fi
if test -r Ns_Env.3; then
    rm -f Ns_Env.3.*
    $ZIP Ns_Env.3
    rm -f Ns_CopyEnviron.3 Ns_CopyEnviron.3.* 
    rm -f Ns_GetEnviron.3 Ns_GetEnviron.3.* 
    ln $S Ns_Env.3$Z Ns_CopyEnviron.3$Z 
    ln $S Ns_Env.3$Z Ns_GetEnviron.3$Z 
fi
if test -r Ns_Exec.3; then
    rm -f Ns_Exec.3.*
    $ZIP Ns_Exec.3
    rm -f Ns_ExecArgblk.3 Ns_ExecArgblk.3.* 
    rm -f Ns_ExecArgv.3 Ns_ExecArgv.3.* 
    rm -f Ns_ExecProc.3 Ns_ExecProc.3.* 
    rm -f Ns_ExecProcess.3 Ns_ExecProcess.3.* 
    rm -f Ns_Fork.3 Ns_Fork.3.* 
    rm -f Ns_WaitForProcess.3 Ns_WaitForProcess.3.* 
    rm -f Ns_WaitProcess.3 Ns_WaitProcess.3.* 
    rm -f ns_fork.3 ns_fork.3.* 
    ln $S Ns_Exec.3$Z Ns_ExecArgblk.3$Z 
    ln $S Ns_Exec.3$Z Ns_ExecArgv.3$Z 
    ln $S Ns_Exec.3$Z Ns_ExecProc.3$Z 
    ln $S Ns_Exec.3$Z Ns_ExecProcess.3$Z 
    ln $S Ns_Exec.3$Z Ns_Fork.3$Z 
    ln $S Ns_Exec.3$Z Ns_WaitForProcess.3$Z 
    ln $S Ns_Exec.3$Z Ns_WaitProcess.3$Z 
    ln $S Ns_Exec.3$Z ns_fork.3$Z 
fi
if test -r Ns_ExtDb.3; then
    rm -f Ns_ExtDb.3.*
    $ZIP Ns_ExtDb.3
    rm -f Ns_ExtDbMsgCodeToName.3 Ns_ExtDbMsgCodeToName.3.* 
    rm -f Ns_ExtDbMsgNameToCode.3 Ns_ExtDbMsgNameToCode.3.* 
    rm -f Ns_ExtDbMsgRequiresArg.3 Ns_ExtDbMsgRequiresArg.3.* 
    ln $S Ns_ExtDb.3$Z Ns_ExtDbMsgCodeToName.3$Z 
    ln $S Ns_ExtDb.3$Z Ns_ExtDbMsgNameToCode.3$Z 
    ln $S Ns_ExtDb.3$Z Ns_ExtDbMsgRequiresArg.3$Z 
fi
if test -r Ns_Fd.3; then
    rm -f Ns_Fd.3.*
    $ZIP Ns_Fd.3
    rm -f Ns_CloseOnExec.3 Ns_CloseOnExec.3.* 
    rm -f Ns_DupHigh.3 Ns_DupHigh.3.* 
    rm -f Ns_NoCloseOnExec.3 Ns_NoCloseOnExec.3.* 
    rm -f ns_closeonexec.3 ns_closeonexec.3.* 
    rm -f ns_duphigh.3 ns_duphigh.3.* 
    ln $S Ns_Fd.3$Z Ns_CloseOnExec.3$Z 
    ln $S Ns_Fd.3$Z Ns_DupHigh.3$Z 
    ln $S Ns_Fd.3$Z Ns_NoCloseOnExec.3$Z 
    ln $S Ns_Fd.3$Z ns_closeonexec.3$Z 
    ln $S Ns_Fd.3$Z ns_duphigh.3$Z 
fi
if test -r Ns_Fetch.3; then
    rm -f Ns_Fetch.3.*
    $ZIP Ns_Fetch.3
    rm -f Ns_FetchPage.3 Ns_FetchPage.3.* 
    rm -f Ns_FetchURL.3 Ns_FetchURL.3.* 
    ln $S Ns_Fetch.3$Z Ns_FetchPage.3$Z 
    ln $S Ns_Fetch.3$Z Ns_FetchURL.3$Z 
fi
if test -r Ns_Filter.3; then
    rm -f Ns_Filter.3.*
    $ZIP Ns_Filter.3
    rm -f Ns_RegisterCleanup.3 Ns_RegisterCleanup.3.* 
    rm -f Ns_RegisterConnCleanup.3 Ns_RegisterConnCleanup.3.* 
    rm -f Ns_RegisterFilter.3 Ns_RegisterFilter.3.* 
    rm -f Ns_RegisterServerTrace.3 Ns_RegisterServerTrace.3.* 
    ln $S Ns_Filter.3$Z Ns_RegisterCleanup.3$Z 
    ln $S Ns_Filter.3$Z Ns_RegisterConnCleanup.3$Z 
    ln $S Ns_Filter.3$Z Ns_RegisterFilter.3$Z 
    ln $S Ns_Filter.3$Z Ns_RegisterServerTrace.3$Z 
fi
if test -r Ns_HttpTime.3; then
    rm -f Ns_HttpTime.3.*
    $ZIP Ns_HttpTime.3
    rm -f Ns_ParseHttpTime.3 Ns_ParseHttpTime.3.* 
    ln $S Ns_HttpTime.3$Z Ns_ParseHttpTime.3$Z 
fi
if test -r Ns_Htuu.3; then
    rm -f Ns_Htuu.3.*
    $ZIP Ns_Htuu.3
    rm -f Ns_HtuuDecode.3 Ns_HtuuDecode.3.* 
    rm -f Ns_HtuuEncode.3 Ns_HtuuEncode.3.* 
    ln $S Ns_Htuu.3$Z Ns_HtuuDecode.3$Z 
    ln $S Ns_Htuu.3$Z Ns_HtuuEncode.3$Z 
fi
if test -r Ns_Index.3; then
    rm -f Ns_Index.3.*
    $ZIP Ns_Index.3
    rm -f Ns_IndexAdd.3 Ns_IndexAdd.3.* 
    rm -f Ns_IndexDel.3 Ns_IndexDel.3.* 
    rm -f Ns_IndexDestroy.3 Ns_IndexDestroy.3.* 
    rm -f Ns_IndexDup.3 Ns_IndexDup.3.* 
    rm -f Ns_IndexEl.3 Ns_IndexEl.3.* 
    rm -f Ns_IndexFind.3 Ns_IndexFind.3.* 
    rm -f Ns_IndexFindInf.3 Ns_IndexFindInf.3.* 
    rm -f Ns_IndexFindMultiple.3 Ns_IndexFindMultiple.3.* 
    rm -f Ns_IndexInit.3 Ns_IndexInit.3.* 
    rm -f Ns_IndexIntInit.3 Ns_IndexIntInit.3.* 
    rm -f Ns_IndexStringAppend.3 Ns_IndexStringAppend.3.* 
    rm -f Ns_IndexStringDestroy.3 Ns_IndexStringDestroy.3.* 
    rm -f Ns_IndexStringDup.3 Ns_IndexStringDup.3.* 
    rm -f Ns_IndexStringInit.3 Ns_IndexStringInit.3.* 
    rm -f Ns_IndexStringTrunc.3 Ns_IndexStringTrunc.3.* 
    rm -f Ns_IndexTrunc.3 Ns_IndexTrunc.3.* 
    ln $S Ns_Index.3$Z Ns_IndexAdd.3$Z 
    ln $S Ns_Index.3$Z Ns_IndexDel.3$Z 
    ln $S Ns_Index.3$Z Ns_IndexDestroy.3$Z 
    ln $S Ns_Index.3$Z Ns_IndexDup.3$Z 
    ln $S Ns_Index.3$Z Ns_IndexEl.3$Z 
    ln $S Ns_Index.3$Z Ns_IndexFind.3$Z 
    ln $S Ns_Index.3$Z Ns_IndexFindInf.3$Z 
    ln $S Ns_Index.3$Z Ns_IndexFindMultiple.3$Z 
    ln $S Ns_Index.3$Z Ns_IndexInit.3$Z 
    ln $S Ns_Index.3$Z Ns_IndexIntInit.3$Z 
    ln $S Ns_Index.3$Z Ns_IndexStringAppend.3$Z 
    ln $S Ns_Index.3$Z Ns_IndexStringDestroy.3$Z 
    ln $S Ns_Index.3$Z Ns_IndexStringDup.3$Z 
    ln $S Ns_Index.3$Z Ns_IndexStringInit.3$Z 
    ln $S Ns_Index.3$Z Ns_IndexStringTrunc.3$Z 
    ln $S Ns_Index.3$Z Ns_IndexTrunc.3$Z 
fi
if test -r Ns_InetAddr.3; then
    rm -f Ns_InetAddr.3.*
    $ZIP Ns_InetAddr.3
    rm -f Ns_GetAddrByHost.3 Ns_GetAddrByHost.3.* 
    rm -f Ns_GetHostByAddr.3 Ns_GetHostByAddr.3.* 
    ln $S Ns_InetAddr.3$Z Ns_GetAddrByHost.3$Z 
    ln $S Ns_InetAddr.3$Z Ns_GetHostByAddr.3$Z 
fi
if test -r Ns_Info.3; then
    rm -f Ns_Info.3.*
    $ZIP Ns_Info.3
    rm -f Ns_HomePath.3 Ns_HomePath.3.* 
    rm -f Ns_InfoAddress.3 Ns_InfoAddress.3.* 
    rm -f Ns_InfoBootTime.3 Ns_InfoBootTime.3.* 
    rm -f Ns_InfoBuildDate.3 Ns_InfoBuildDate.3.* 
    rm -f Ns_InfoConfigFile.3 Ns_InfoConfigFile.3.* 
    rm -f Ns_InfoErrorLog.3 Ns_InfoErrorLog.3.* 
    rm -f Ns_InfoHomePath.3 Ns_InfoHomePath.3.* 
    rm -f Ns_InfoHostname.3 Ns_InfoHostname.3.* 
    rm -f Ns_InfoLabel.3 Ns_InfoLabel.3.* 
    rm -f Ns_InfoNameOfExecutable.3 Ns_InfoNameOfExecutable.3.* 
    rm -f Ns_InfoPid.3 Ns_InfoPid.3.* 
    rm -f Ns_InfoPlatform.3 Ns_InfoPlatform.3.* 
    rm -f Ns_InfoServerName.3 Ns_InfoServerName.3.* 
    rm -f Ns_InfoServerVersion.3 Ns_InfoServerVersion.3.* 
    rm -f Ns_InfoServersStarted.3 Ns_InfoServersStarted.3.* 
    rm -f Ns_InfoShutdownPending.3 Ns_InfoShutdownPending.3.* 
    rm -f Ns_InfoStarted.3 Ns_InfoStarted.3.* 
    rm -f Ns_InfoTag.3 Ns_InfoTag.3.* 
    rm -f Ns_InfoUptime.3 Ns_InfoUptime.3.* 
    rm -f Ns_LibPath.3 Ns_LibPath.3.* 
    rm -f Ns_PageRoot.3 Ns_PageRoot.3.* 
    ln $S Ns_Info.3$Z Ns_HomePath.3$Z 
    ln $S Ns_Info.3$Z Ns_InfoAddress.3$Z 
    ln $S Ns_Info.3$Z Ns_InfoBootTime.3$Z 
    ln $S Ns_Info.3$Z Ns_InfoBuildDate.3$Z 
    ln $S Ns_Info.3$Z Ns_InfoConfigFile.3$Z 
    ln $S Ns_Info.3$Z Ns_InfoErrorLog.3$Z 
    ln $S Ns_Info.3$Z Ns_InfoHomePath.3$Z 
    ln $S Ns_Info.3$Z Ns_InfoHostname.3$Z 
    ln $S Ns_Info.3$Z Ns_InfoLabel.3$Z 
    ln $S Ns_Info.3$Z Ns_InfoNameOfExecutable.3$Z 
    ln $S Ns_Info.3$Z Ns_InfoPid.3$Z 
    ln $S Ns_Info.3$Z Ns_InfoPlatform.3$Z 
    ln $S Ns_Info.3$Z Ns_InfoServerName.3$Z 
    ln $S Ns_Info.3$Z Ns_InfoServerVersion.3$Z 
    ln $S Ns_Info.3$Z Ns_InfoServersStarted.3$Z 
    ln $S Ns_Info.3$Z Ns_InfoShutdownPending.3$Z 
    ln $S Ns_Info.3$Z Ns_InfoStarted.3$Z 
    ln $S Ns_Info.3$Z Ns_InfoTag.3$Z 
    ln $S Ns_Info.3$Z Ns_InfoUptime.3$Z 
    ln $S Ns_Info.3$Z Ns_LibPath.3$Z 
    ln $S Ns_Info.3$Z Ns_PageRoot.3$Z 
fi
if test -r Ns_IntPrint.3; then
    rm -f Ns_IntPrint.3.*
    $ZIP Ns_IntPrint.3
fi
if test -r Ns_List.3; then
    rm -f Ns_List.3.*
    $ZIP Ns_List.3
    rm -f Ns_ListCons.3 Ns_ListCons.3.* 
    rm -f Ns_ListCopy.3 Ns_ListCopy.3.* 
    rm -f Ns_ListDeleteDuplicates.3 Ns_ListDeleteDuplicates.3.* 
    rm -f Ns_ListDeleteIf.3 Ns_ListDeleteIf.3.* 
    rm -f Ns_ListDeleteLowElements.3 Ns_ListDeleteLowElements.3.* 
    rm -f Ns_ListDeleteWithTest.3 Ns_ListDeleteWithTest.3.* 
    rm -f Ns_ListFree.3 Ns_ListFree.3.* 
    rm -f Ns_ListLast.3 Ns_ListLast.3.* 
    rm -f Ns_ListLength.3 Ns_ListLength.3.* 
    rm -f Ns_ListMapcar.3 Ns_ListMapcar.3.* 
    rm -f Ns_ListNconc.3 Ns_ListNconc.3.* 
    rm -f Ns_ListNmapcar.3 Ns_ListNmapcar.3.* 
    rm -f Ns_ListNreverse.3 Ns_ListNreverse.3.* 
    rm -f Ns_ListPrint.3 Ns_ListPrint.3.* 
    rm -f Ns_ListSort.3 Ns_ListSort.3.* 
    rm -f Ns_ListWeightSort.3 Ns_ListWeightSort.3.* 
    ln $S Ns_List.3$Z Ns_ListCons.3$Z 
    ln $S Ns_List.3$Z Ns_ListCopy.3$Z 
    ln $S Ns_List.3$Z Ns_ListDeleteDuplicates.3$Z 
    ln $S Ns_List.3$Z Ns_ListDeleteIf.3$Z 
    ln $S Ns_List.3$Z Ns_ListDeleteLowElements.3$Z 
    ln $S Ns_List.3$Z Ns_ListDeleteWithTest.3$Z 
    ln $S Ns_List.3$Z Ns_ListFree.3$Z 
    ln $S Ns_List.3$Z Ns_ListLast.3$Z 
    ln $S Ns_List.3$Z Ns_ListLength.3$Z 
    ln $S Ns_List.3$Z Ns_ListMapcar.3$Z 
    ln $S Ns_List.3$Z Ns_ListNconc.3$Z 
    ln $S Ns_List.3$Z Ns_ListNmapcar.3$Z 
    ln $S Ns_List.3$Z Ns_ListNreverse.3$Z 
    ln $S Ns_List.3$Z Ns_ListPrint.3$Z 
    ln $S Ns_List.3$Z Ns_ListSort.3$Z 
    ln $S Ns_List.3$Z Ns_ListWeightSort.3$Z 
fi
if test -r Ns_Location.3; then
    rm -f Ns_Location.3.*
    $ZIP Ns_Location.3
    rm -f Ns_SetConnLocationProc.3 Ns_SetConnLocationProc.3.* 
    rm -f Ns_SetLocationProc.3 Ns_SetLocationProc.3.* 
    ln $S Ns_Location.3$Z Ns_SetConnLocationProc.3$Z 
    ln $S Ns_Location.3$Z Ns_SetLocationProc.3$Z 
fi
if test -r Ns_Log.3; then
    rm -f Ns_Log.3.*
    $ZIP Ns_Log.3
    rm -f Ns_Fatal.3 Ns_Fatal.3.* 
    rm -f Ns_LogRoll.3 Ns_LogRoll.3.* 
    rm -f Ns_LogTime.3 Ns_LogTime.3.* 
    rm -f Ns_LogTime2.3 Ns_LogTime2.3.* 
    rm -f Ns_TclLogError.3 Ns_TclLogError.3.* 
    rm -f Ns_TclLogErrorRequest.3 Ns_TclLogErrorRequest.3.* 
    rm -f ns_serverLog.3 ns_serverLog.3.* 
    ln $S Ns_Log.3$Z Ns_Fatal.3$Z 
    ln $S Ns_Log.3$Z Ns_LogRoll.3$Z 
    ln $S Ns_Log.3$Z Ns_LogTime.3$Z 
    ln $S Ns_Log.3$Z Ns_LogTime2.3$Z 
    ln $S Ns_Log.3$Z Ns_TclLogError.3$Z 
    ln $S Ns_Log.3$Z Ns_TclLogErrorRequest.3$Z 
    ln $S Ns_Log.3$Z ns_serverLog.3$Z 
fi
if test -r Ns_Master.3; then
    rm -f Ns_Master.3.*
    $ZIP Ns_Master.3
    rm -f Ns_MasterLock.3 Ns_MasterLock.3.* 
    rm -f Ns_MasterUnlock.3 Ns_MasterUnlock.3.* 
    ln $S Ns_Master.3$Z Ns_MasterLock.3$Z 
    ln $S Ns_Master.3$Z Ns_MasterUnlock.3$Z 
fi
if test -r Ns_Mime.3; then
    rm -f Ns_Mime.3.*
    $ZIP Ns_Mime.3
    rm -f Ns_GetMimeType.3 Ns_GetMimeType.3.* 
    ln $S Ns_Mime.3$Z Ns_GetMimeType.3$Z 
fi
if test -r Ns_Module.3; then
    rm -f Ns_Module.3.*
    $ZIP Ns_Module.3
    rm -f Ns_ModuleGetSymbol.3 Ns_ModuleGetSymbol.3.* 
    rm -f Ns_ModuleLoad.3 Ns_ModuleLoad.3.* 
    rm -f Ns_ModulePath.3 Ns_ModulePath.3.* 
    rm -f Ns_ModuleSymbol.3 Ns_ModuleSymbol.3.* 
    rm -f Ns_RegisterModule.3 Ns_RegisterModule.3.* 
    ln $S Ns_Module.3$Z Ns_ModuleGetSymbol.3$Z 
    ln $S Ns_Module.3$Z Ns_ModuleLoad.3$Z 
    ln $S Ns_Module.3$Z Ns_ModulePath.3$Z 
    ln $S Ns_Module.3$Z Ns_ModuleSymbol.3$Z 
    ln $S Ns_Module.3$Z Ns_RegisterModule.3$Z 
fi
if test -r Ns_Mutex.3; then
    rm -f Ns_Mutex.3.*
    $ZIP Ns_Mutex.3
    rm -f Ns_DestroyMutex.3 Ns_DestroyMutex.3.* 
    rm -f Ns_InitializeMutex.3 Ns_InitializeMutex.3.* 
    rm -f Ns_LockMutex.3 Ns_LockMutex.3.* 
    rm -f Ns_MutexDestroy.3 Ns_MutexDestroy.3.* 
    rm -f Ns_MutexInit.3 Ns_MutexInit.3.* 
    rm -f Ns_MutexList.3 Ns_MutexList.3.* 
    rm -f Ns_MutexLock.3 Ns_MutexLock.3.* 
    rm -f Ns_MutexSetName.3 Ns_MutexSetName.3.* 
    rm -f Ns_MutexSetName2.3 Ns_MutexSetName2.3.* 
    rm -f Ns_MutexTryLock.3 Ns_MutexTryLock.3.* 
    rm -f Ns_MutexUnlock.3 Ns_MutexUnlock.3.* 
    rm -f Ns_UnlockMutex.3 Ns_UnlockMutex.3.* 
    ln $S Ns_Mutex.3$Z Ns_DestroyMutex.3$Z 
    ln $S Ns_Mutex.3$Z Ns_InitializeMutex.3$Z 
    ln $S Ns_Mutex.3$Z Ns_LockMutex.3$Z 
    ln $S Ns_Mutex.3$Z Ns_MutexDestroy.3$Z 
    ln $S Ns_Mutex.3$Z Ns_MutexInit.3$Z 
    ln $S Ns_Mutex.3$Z Ns_MutexList.3$Z 
    ln $S Ns_Mutex.3$Z Ns_MutexLock.3$Z 
    ln $S Ns_Mutex.3$Z Ns_MutexSetName.3$Z 
    ln $S Ns_Mutex.3$Z Ns_MutexSetName2.3$Z 
    ln $S Ns_Mutex.3$Z Ns_MutexTryLock.3$Z 
    ln $S Ns_Mutex.3$Z Ns_MutexUnlock.3$Z 
    ln $S Ns_Mutex.3$Z Ns_UnlockMutex.3$Z 
fi
if test -r Ns_Nsd.3; then
    rm -f Ns_Nsd.3.*
    $ZIP Ns_Nsd.3
    rm -f Ns_Main.3 Ns_Main.3.* 
    rm -f Ns_StopServer.3 Ns_StopServer.3.* 
    rm -f Ns_WaitForStartup.3 Ns_WaitForStartup.3.* 
    ln $S Ns_Nsd.3$Z Ns_Main.3$Z 
    ln $S Ns_Nsd.3$Z Ns_StopServer.3$Z 
    ln $S Ns_Nsd.3$Z Ns_WaitForStartup.3$Z 
fi
if test -r Ns_Pathname.3; then
    rm -f Ns_Pathname.3.*
    $ZIP Ns_Pathname.3
    rm -f Ns_MakePath.3 Ns_MakePath.3.* 
    rm -f Ns_NormalizePath.3 Ns_NormalizePath.3.* 
    rm -f Ns_PathIsAbsolute.3 Ns_PathIsAbsolute.3.* 
    ln $S Ns_Pathname.3$Z Ns_MakePath.3$Z 
    ln $S Ns_Pathname.3$Z Ns_NormalizePath.3$Z 
    ln $S Ns_Pathname.3$Z Ns_PathIsAbsolute.3$Z 
fi
if test -r Ns_Pool.3; then
    rm -f Ns_Pool.3.*
    $ZIP Ns_Pool.3
    rm -f Ns_PoolAlloc.3 Ns_PoolAlloc.3.* 
    rm -f Ns_PoolBlockSize.3 Ns_PoolBlockSize.3.* 
    rm -f Ns_PoolCalloc.3 Ns_PoolCalloc.3.* 
    rm -f Ns_PoolCreate.3 Ns_PoolCreate.3.* 
    rm -f Ns_PoolDestroy.3 Ns_PoolDestroy.3.* 
    rm -f Ns_PoolFlush.3 Ns_PoolFlush.3.* 
    rm -f Ns_PoolFree.3 Ns_PoolFree.3.* 
    rm -f Ns_PoolRealloc.3 Ns_PoolRealloc.3.* 
    rm -f Ns_PoolStrCopy.3 Ns_PoolStrCopy.3.* 
    rm -f Ns_PoolStrDup.3 Ns_PoolStrDup.3.* 
    ln $S Ns_Pool.3$Z Ns_PoolAlloc.3$Z 
    ln $S Ns_Pool.3$Z Ns_PoolBlockSize.3$Z 
    ln $S Ns_Pool.3$Z Ns_PoolCalloc.3$Z 
    ln $S Ns_Pool.3$Z Ns_PoolCreate.3$Z 
    ln $S Ns_Pool.3$Z Ns_PoolDestroy.3$Z 
    ln $S Ns_Pool.3$Z Ns_PoolFlush.3$Z 
    ln $S Ns_Pool.3$Z Ns_PoolFree.3$Z 
    ln $S Ns_Pool.3$Z Ns_PoolRealloc.3$Z 
    ln $S Ns_Pool.3$Z Ns_PoolStrCopy.3$Z 
    ln $S Ns_Pool.3$Z Ns_PoolStrDup.3$Z 
fi
if test -r Ns_ProcInfo.3; then
    rm -f Ns_ProcInfo.3.*
    $ZIP Ns_ProcInfo.3
    rm -f Ns_GetProcInfo.3 Ns_GetProcInfo.3.* 
    rm -f Ns_RegisterProcInfo.3 Ns_RegisterProcInfo.3.* 
    ln $S Ns_ProcInfo.3$Z Ns_GetProcInfo.3$Z 
    ln $S Ns_ProcInfo.3$Z Ns_RegisterProcInfo.3$Z 
fi
if test -r Ns_QuoteHtml.3; then
    rm -f Ns_QuoteHtml.3.*
    $ZIP Ns_QuoteHtml.3
fi
if test -r Ns_RWLock.3; then
    rm -f Ns_RWLock.3.*
    $ZIP Ns_RWLock.3
    rm -f Ns_RWLockDestroy.3 Ns_RWLockDestroy.3.* 
    rm -f Ns_RWLockInit.3 Ns_RWLockInit.3.* 
    rm -f Ns_RWLockRdLock.3 Ns_RWLockRdLock.3.* 
    rm -f Ns_RWLockUnlock.3 Ns_RWLockUnlock.3.* 
    rm -f Ns_RWLockWrLock.3 Ns_RWLockWrLock.3.* 
    ln $S Ns_RWLock.3$Z Ns_RWLockDestroy.3$Z 
    ln $S Ns_RWLock.3$Z Ns_RWLockInit.3$Z 
    ln $S Ns_RWLock.3$Z Ns_RWLockRdLock.3$Z 
    ln $S Ns_RWLock.3$Z Ns_RWLockUnlock.3$Z 
    ln $S Ns_RWLock.3$Z Ns_RWLockWrLock.3$Z 
fi
if test -r Ns_Rand.3; then
    rm -f Ns_Rand.3.*
    $ZIP Ns_Rand.3
    rm -f Ns_DRand.3 Ns_DRand.3.* 
    rm -f Ns_GenSeeds.3 Ns_GenSeeds.3.* 
    ln $S Ns_Rand.3$Z Ns_DRand.3$Z 
    ln $S Ns_Rand.3$Z Ns_GenSeeds.3$Z 
fi
if test -r Ns_Reentrant.3; then
    rm -f Ns_Reentrant.3.*
    $ZIP Ns_Reentrant.3
    rm -f ns_asctime.3 ns_asctime.3.* 
    rm -f ns_ctime.3 ns_ctime.3.* 
    rm -f ns_gmtime.3 ns_gmtime.3.* 
    rm -f ns_inet_ntoa.3 ns_inet_ntoa.3.* 
    rm -f ns_localtime.3 ns_localtime.3.* 
    rm -f ns_readdir.3 ns_readdir.3.* 
    rm -f ns_strtok.3 ns_strtok.3.* 
    ln $S Ns_Reentrant.3$Z ns_asctime.3$Z 
    ln $S Ns_Reentrant.3$Z ns_ctime.3$Z 
    ln $S Ns_Reentrant.3$Z ns_gmtime.3$Z 
    ln $S Ns_Reentrant.3$Z ns_inet_ntoa.3$Z 
    ln $S Ns_Reentrant.3$Z ns_localtime.3$Z 
    ln $S Ns_Reentrant.3$Z ns_readdir.3$Z 
    ln $S Ns_Reentrant.3$Z ns_strtok.3$Z 
fi
if test -r Ns_Register.3; then
    rm -f Ns_Register.3.*
    $ZIP Ns_Register.3
    rm -f Ns_RegisterAtExit.3 Ns_RegisterAtExit.3.* 
    rm -f Ns_RegisterAtPreStartup.3 Ns_RegisterAtPreStartup.3.* 
    rm -f Ns_RegisterAtReady.3 Ns_RegisterAtReady.3.* 
    rm -f Ns_RegisterAtServerShutdown.3 Ns_RegisterAtServerShutdown.3.* 
    rm -f Ns_RegisterAtShutdown.3 Ns_RegisterAtShutdown.3.* 
    rm -f Ns_RegisterAtSignal.3 Ns_RegisterAtSignal.3.* 
    rm -f Ns_RegisterAtStartup.3 Ns_RegisterAtStartup.3.* 
    rm -f Ns_RegisterServerShutdown.3 Ns_RegisterServerShutdown.3.* 
    rm -f Ns_RegisterShutdown.3 Ns_RegisterShutdown.3.* 
    ln $S Ns_Register.3$Z Ns_RegisterAtExit.3$Z 
    ln $S Ns_Register.3$Z Ns_RegisterAtPreStartup.3$Z 
    ln $S Ns_Register.3$Z Ns_RegisterAtReady.3$Z 
    ln $S Ns_Register.3$Z Ns_RegisterAtServerShutdown.3$Z 
    ln $S Ns_Register.3$Z Ns_RegisterAtShutdown.3$Z 
    ln $S Ns_Register.3$Z Ns_RegisterAtSignal.3$Z 
    ln $S Ns_Register.3$Z Ns_RegisterAtStartup.3$Z 
    ln $S Ns_Register.3$Z Ns_RegisterServerShutdown.3$Z 
    ln $S Ns_Register.3$Z Ns_RegisterShutdown.3$Z 
fi
if test -r Ns_Request.3; then
    rm -f Ns_Request.3.*
    $ZIP Ns_Request.3
    rm -f Ns_FreeRequest.3 Ns_FreeRequest.3.* 
    rm -f Ns_ParseHeader.3 Ns_ParseHeader.3.* 
    rm -f Ns_ParseRequest.3 Ns_ParseRequest.3.* 
    rm -f Ns_QueryToSet.3 Ns_QueryToSet.3.* 
    rm -f Ns_SetRequestUrl.3 Ns_SetRequestUrl.3.* 
    ln $S Ns_Request.3$Z Ns_FreeRequest.3$Z 
    ln $S Ns_Request.3$Z Ns_ParseHeader.3$Z 
    ln $S Ns_Request.3$Z Ns_ParseRequest.3$Z 
    ln $S Ns_Request.3$Z Ns_QueryToSet.3$Z 
    ln $S Ns_Request.3$Z Ns_SetRequestUrl.3$Z 
fi
if test -r Ns_RollFile.3; then
    rm -f Ns_RollFile.3.*
    $ZIP Ns_RollFile.3
    rm -f Ns_PurgeFiles.3 Ns_PurgeFiles.3.* 
    rm -f Ns_RollFileByDate.3 Ns_RollFileByDate.3.* 
    ln $S Ns_RollFile.3$Z Ns_PurgeFiles.3$Z 
    ln $S Ns_RollFile.3$Z Ns_RollFileByDate.3$Z 
fi
if test -r Ns_Sched.3; then
    rm -f Ns_Sched.3.*
    $ZIP Ns_Sched.3
    rm -f Ns_After.3 Ns_After.3.* 
    rm -f Ns_Cancel.3 Ns_Cancel.3.* 
    rm -f Ns_Pause.3 Ns_Pause.3.* 
    rm -f Ns_Resume.3 Ns_Resume.3.* 
    rm -f Ns_ScheduleDaily.3 Ns_ScheduleDaily.3.* 
    rm -f Ns_ScheduleProc.3 Ns_ScheduleProc.3.* 
    rm -f Ns_ScheduleProcEx.3 Ns_ScheduleProcEx.3.* 
    rm -f Ns_ScheduleWeekly.3 Ns_ScheduleWeekly.3.* 
    rm -f Ns_UnscheduleProc.3 Ns_UnscheduleProc.3.* 
    ln $S Ns_Sched.3$Z Ns_After.3$Z 
    ln $S Ns_Sched.3$Z Ns_Cancel.3$Z 
    ln $S Ns_Sched.3$Z Ns_Pause.3$Z 
    ln $S Ns_Sched.3$Z Ns_Resume.3$Z 
    ln $S Ns_Sched.3$Z Ns_ScheduleDaily.3$Z 
    ln $S Ns_Sched.3$Z Ns_ScheduleProc.3$Z 
    ln $S Ns_Sched.3$Z Ns_ScheduleProcEx.3$Z 
    ln $S Ns_Sched.3$Z Ns_ScheduleWeekly.3$Z 
    ln $S Ns_Sched.3$Z Ns_UnscheduleProc.3$Z 
fi
if test -r Ns_Sema.3; then
    rm -f Ns_Sema.3.*
    $ZIP Ns_Sema.3
    rm -f Ns_SemaDestroy.3 Ns_SemaDestroy.3.* 
    rm -f Ns_SemaInit.3 Ns_SemaInit.3.* 
    rm -f Ns_SemaPost.3 Ns_SemaPost.3.* 
    rm -f Ns_SemaWait.3 Ns_SemaWait.3.* 
    ln $S Ns_Sema.3$Z Ns_SemaDestroy.3$Z 
    ln $S Ns_Sema.3$Z Ns_SemaInit.3$Z 
    ln $S Ns_Sema.3$Z Ns_SemaPost.3$Z 
    ln $S Ns_Sema.3$Z Ns_SemaWait.3$Z 
fi
if test -r Ns_ServerSpecific.3; then
    rm -f Ns_ServerSpecific.3.*
    $ZIP Ns_ServerSpecific.3
    rm -f Ns_ServerSpecificAlloc.3 Ns_ServerSpecificAlloc.3.* 
    rm -f Ns_ServerSpecificDestroy.3 Ns_ServerSpecificDestroy.3.* 
    rm -f Ns_ServerSpecificGet.3 Ns_ServerSpecificGet.3.* 
    rm -f Ns_ServerSpecificSet.3 Ns_ServerSpecificSet.3.* 
    ln $S Ns_ServerSpecific.3$Z Ns_ServerSpecificAlloc.3$Z 
    ln $S Ns_ServerSpecific.3$Z Ns_ServerSpecificDestroy.3$Z 
    ln $S Ns_ServerSpecific.3$Z Ns_ServerSpecificGet.3$Z 
    ln $S Ns_ServerSpecific.3$Z Ns_ServerSpecificSet.3$Z 
fi
if test -r Ns_Set.3; then
    rm -f Ns_Set.3.*
    $ZIP Ns_Set.3
    rm -f Ns_SetCopy.3 Ns_SetCopy.3.* 
    rm -f Ns_SetCreate.3 Ns_SetCreate.3.* 
    rm -f Ns_SetDelete.3 Ns_SetDelete.3.* 
    rm -f Ns_SetDeleteKey.3 Ns_SetDeleteKey.3.* 
    rm -f Ns_SetFind.3 Ns_SetFind.3.* 
    rm -f Ns_SetFindCmp.3 Ns_SetFindCmp.3.* 
    rm -f Ns_SetFree.3 Ns_SetFree.3.* 
    rm -f Ns_SetGet.3 Ns_SetGet.3.* 
    rm -f Ns_SetGetCmp.3 Ns_SetGetCmp.3.* 
    rm -f Ns_SetIDeleteKey.3 Ns_SetIDeleteKey.3.* 
    rm -f Ns_SetIFind.3 Ns_SetIFind.3.* 
    rm -f Ns_SetIGet.3 Ns_SetIGet.3.* 
    rm -f Ns_SetIUnique.3 Ns_SetIUnique.3.* 
    rm -f Ns_SetListFind.3 Ns_SetListFind.3.* 
    rm -f Ns_SetListFree.3 Ns_SetListFree.3.* 
    rm -f Ns_SetMerge.3 Ns_SetMerge.3.* 
    rm -f Ns_SetMove.3 Ns_SetMove.3.* 
    rm -f Ns_SetPrint.3 Ns_SetPrint.3.* 
    rm -f Ns_SetPut.3 Ns_SetPut.3.* 
    rm -f Ns_SetPutValue.3 Ns_SetPutValue.3.* 
    rm -f Ns_SetSplit.3 Ns_SetSplit.3.* 
    rm -f Ns_SetTrunc.3 Ns_SetTrunc.3.* 
    rm -f Ns_SetUnique.3 Ns_SetUnique.3.* 
    rm -f Ns_SetUniqueCmp.3 Ns_SetUniqueCmp.3.* 
    rm -f Ns_SetUpdate.3 Ns_SetUpdate.3.* 
    ln $S Ns_Set.3$Z Ns_SetCopy.3$Z 
    ln $S Ns_Set.3$Z Ns_SetCreate.3$Z 
    ln $S Ns_Set.3$Z Ns_SetDelete.3$Z 
    ln $S Ns_Set.3$Z Ns_SetDeleteKey.3$Z 
    ln $S Ns_Set.3$Z Ns_SetFind.3$Z 
    ln $S Ns_Set.3$Z Ns_SetFindCmp.3$Z 
    ln $S Ns_Set.3$Z Ns_SetFree.3$Z 
    ln $S Ns_Set.3$Z Ns_SetGet.3$Z 
    ln $S Ns_Set.3$Z Ns_SetGetCmp.3$Z 
    ln $S Ns_Set.3$Z Ns_SetIDeleteKey.3$Z 
    ln $S Ns_Set.3$Z Ns_SetIFind.3$Z 
    ln $S Ns_Set.3$Z Ns_SetIGet.3$Z 
    ln $S Ns_Set.3$Z Ns_SetIUnique.3$Z 
    ln $S Ns_Set.3$Z Ns_SetListFind.3$Z 
    ln $S Ns_Set.3$Z Ns_SetListFree.3$Z 
    ln $S Ns_Set.3$Z Ns_SetMerge.3$Z 
    ln $S Ns_Set.3$Z Ns_SetMove.3$Z 
    ln $S Ns_Set.3$Z Ns_SetPrint.3$Z 
    ln $S Ns_Set.3$Z Ns_SetPut.3$Z 
    ln $S Ns_Set.3$Z Ns_SetPutValue.3$Z 
    ln $S Ns_Set.3$Z Ns_SetSplit.3$Z 
    ln $S Ns_Set.3$Z Ns_SetTrunc.3$Z 
    ln $S Ns_Set.3$Z Ns_SetUnique.3$Z 
    ln $S Ns_Set.3$Z Ns_SetUniqueCmp.3$Z 
    ln $S Ns_Set.3$Z Ns_SetUpdate.3$Z 
fi
if test -r Ns_Signal.3; then
    rm -f Ns_Signal.3.*
    $ZIP Ns_Signal.3
    rm -f ns_sigmask.3 ns_sigmask.3.* 
    if test "${CASEINSENSITIVEFS:-}" != "1"; then rm -f ns_signal.3 ns_signal.3.* ; fi
    rm -f ns_sigwait.3 ns_sigwait.3.* 
    ln $S Ns_Signal.3$Z ns_sigmask.3$Z 
    if test "${CASEINSENSITIVEFS:-}" != "1"; then ln $S Ns_Signal.3$Z ns_signal.3$Z ; fi
    ln $S Ns_Signal.3$Z ns_sigwait.3$Z 
fi
if test -r Ns_Sock.3; then
    rm -f Ns_Sock.3.*
    $ZIP Ns_Sock.3
    rm -f Ns_BindSock.3 Ns_BindSock.3.* 
    rm -f Ns_GetSockAddr.3 Ns_GetSockAddr.3.* 
    rm -f Ns_SockAccept.3 Ns_SockAccept.3.* 
    rm -f Ns_SockAsyncConnect.3 Ns_SockAsyncConnect.3.* 
    rm -f Ns_SockAsyncConnect2.3 Ns_SockAsyncConnect2.3.* 
    rm -f Ns_SockBind.3 Ns_SockBind.3.* 
    rm -f Ns_SockCloseLater.3 Ns_SockCloseLater.3.* 
    rm -f Ns_SockConnect.3 Ns_SockConnect.3.* 
    rm -f Ns_SockConnect2.3 Ns_SockConnect2.3.* 
    rm -f Ns_SockListen.3 Ns_SockListen.3.* 
    rm -f Ns_SockListenEx.3 Ns_SockListenEx.3.* 
    rm -f Ns_SockPipe.3 Ns_SockPipe.3.* 
    rm -f Ns_SockSetBlocking.3 Ns_SockSetBlocking.3.* 
    rm -f Ns_SockSetNonBlocking.3 Ns_SockSetNonBlocking.3.* 
    rm -f Ns_SockStrError.3 Ns_SockStrError.3.* 
    rm -f Ns_SockTimedConnect.3 Ns_SockTimedConnect.3.* 
    rm -f Ns_SockTimedConnect2.3 Ns_SockTimedConnect2.3.* 
    rm -f ns_pipe.3 ns_pipe.3.* 
    rm -f ns_sockpair.3 ns_sockpair.3.* 
    ln $S Ns_Sock.3$Z Ns_BindSock.3$Z 
    ln $S Ns_Sock.3$Z Ns_GetSockAddr.3$Z 
    ln $S Ns_Sock.3$Z Ns_SockAccept.3$Z 
    ln $S Ns_Sock.3$Z Ns_SockAsyncConnect.3$Z 
    ln $S Ns_Sock.3$Z Ns_SockAsyncConnect2.3$Z 
    ln $S Ns_Sock.3$Z Ns_SockBind.3$Z 
    ln $S Ns_Sock.3$Z Ns_SockCloseLater.3$Z 
    ln $S Ns_Sock.3$Z Ns_SockConnect.3$Z 
    ln $S Ns_Sock.3$Z Ns_SockConnect2.3$Z 
    ln $S Ns_Sock.3$Z Ns_SockListen.3$Z 
    ln $S Ns_Sock.3$Z Ns_SockListenEx.3$Z 
    ln $S Ns_Sock.3$Z Ns_SockPipe.3$Z 
    ln $S Ns_Sock.3$Z Ns_SockSetBlocking.3$Z 
    ln $S Ns_Sock.3$Z Ns_SockSetNonBlocking.3$Z 
    ln $S Ns_Sock.3$Z Ns_SockStrError.3$Z 
    ln $S Ns_Sock.3$Z Ns_SockTimedConnect.3$Z 
    ln $S Ns_Sock.3$Z Ns_SockTimedConnect2.3$Z 
    ln $S Ns_Sock.3$Z ns_pipe.3$Z 
    ln $S Ns_Sock.3$Z ns_sockpair.3$Z 
fi
if test -r Ns_SockCallback.3; then
    rm -f Ns_SockCallback.3.*
    $ZIP Ns_SockCallback.3
    rm -f Ns_SockCancelCallback.3 Ns_SockCancelCallback.3.* 
    rm -f Ns_SockListenCallback.3 Ns_SockListenCallback.3.* 
    rm -f Ns_SockPortBound.3 Ns_SockPortBound.3.* 
    ln $S Ns_SockCallback.3$Z Ns_SockCancelCallback.3$Z 
    ln $S Ns_SockCallback.3$Z Ns_SockListenCallback.3$Z 
    ln $S Ns_SockCallback.3$Z Ns_SockPortBound.3$Z 
fi
if test -r Ns_SockErrno.3; then
    rm -f Ns_SockErrno.3.*
    $ZIP Ns_SockErrno.3
    rm -f Ns_ClearSockErrno.3 Ns_ClearSockErrno.3.* 
    rm -f Ns_GetSockErrno.3 Ns_GetSockErrno.3.* 
    rm -f Ns_SetSockErrno.3 Ns_SetSockErrno.3.* 
    ln $S Ns_SockErrno.3$Z Ns_ClearSockErrno.3$Z 
    ln $S Ns_SockErrno.3$Z Ns_GetSockErrno.3$Z 
    ln $S Ns_SockErrno.3$Z Ns_SetSockErrno.3$Z 
fi
if test -r Ns_SockIO.3; then
    rm -f Ns_SockIO.3.*
    $ZIP Ns_SockIO.3
    rm -f Ns_SockRecv.3 Ns_SockRecv.3.* 
    rm -f Ns_SockSend.3 Ns_SockSend.3.* 
    rm -f Ns_SockWait.3 Ns_SockWait.3.* 
    ln $S Ns_SockIO.3$Z Ns_SockRecv.3$Z 
    ln $S Ns_SockIO.3$Z Ns_SockSend.3$Z 
    ln $S Ns_SockIO.3$Z Ns_SockWait.3$Z 
fi
if test -r Ns_String.3; then
    rm -f Ns_String.3.*
    $ZIP Ns_String.3
    rm -f Ns_Match.3 Ns_Match.3.* 
    rm -f Ns_NextWord.3 Ns_NextWord.3.* 
    rm -f Ns_StrCaseFind.3 Ns_StrCaseFind.3.* 
    rm -f Ns_StrCopy.3 Ns_StrCopy.3.* 
    rm -f Ns_StrDup.3 Ns_StrDup.3.* 
    rm -f Ns_StrNStr.3 Ns_StrNStr.3.* 
    rm -f Ns_StrToLower.3 Ns_StrToLower.3.* 
    rm -f Ns_StrToUpper.3 Ns_StrToUpper.3.* 
    rm -f Ns_StrTrim.3 Ns_StrTrim.3.* 
    rm -f Ns_StrTrimLeft.3 Ns_StrTrimLeft.3.* 
    rm -f Ns_StrTrimRight.3 Ns_StrTrimRight.3.* 
    rm -f Ns_StringPrint.3 Ns_StringPrint.3.* 
    rm -f ns_strcopy.3 ns_strcopy.3.* 
    rm -f ns_strdup.3 ns_strdup.3.* 
    ln $S Ns_String.3$Z Ns_Match.3$Z 
    ln $S Ns_String.3$Z Ns_NextWord.3$Z 
    ln $S Ns_String.3$Z Ns_StrCaseFind.3$Z 
    ln $S Ns_String.3$Z Ns_StrCopy.3$Z 
    ln $S Ns_String.3$Z Ns_StrDup.3$Z 
    ln $S Ns_String.3$Z Ns_StrNStr.3$Z 
    ln $S Ns_String.3$Z Ns_StrToLower.3$Z 
    ln $S Ns_String.3$Z Ns_StrToUpper.3$Z 
    ln $S Ns_String.3$Z Ns_StrTrim.3$Z 
    ln $S Ns_String.3$Z Ns_StrTrimLeft.3$Z 
    ln $S Ns_String.3$Z Ns_StrTrimRight.3$Z 
    ln $S Ns_String.3$Z Ns_StringPrint.3$Z 
    ln $S Ns_String.3$Z ns_strcopy.3$Z 
    ln $S Ns_String.3$Z ns_strdup.3$Z 
fi
if test -r Ns_TclConn.3; then
    rm -f Ns_TclConn.3.*
    $ZIP Ns_TclConn.3
    rm -f Ns_FreeConnInterp.3 Ns_FreeConnInterp.3.* 
    rm -f Ns_GetConnInterp.3 Ns_GetConnInterp.3.* 
    rm -f Ns_TclGetConn.3 Ns_TclGetConn.3.* 
    rm -f Ns_TclRequest.3 Ns_TclRequest.3.* 
    ln $S Ns_TclConn.3$Z Ns_FreeConnInterp.3$Z 
    ln $S Ns_TclConn.3$Z Ns_GetConnInterp.3$Z 
    ln $S Ns_TclConn.3$Z Ns_TclGetConn.3$Z 
    ln $S Ns_TclConn.3$Z Ns_TclRequest.3$Z 
fi
if test -r Ns_TclDbGetHandle.3; then
    rm -f Ns_TclDbGetHandle.3.*
    $ZIP Ns_TclDbGetHandle.3
fi
if test -r Ns_TclFile.3; then
    rm -f Ns_TclFile.3.*
    $ZIP Ns_TclFile.3
    rm -f Ns_TclGetOpenChannel.3 Ns_TclGetOpenChannel.3.* 
    rm -f Ns_TclGetOpenFd.3 Ns_TclGetOpenFd.3.* 
    ln $S Ns_TclFile.3$Z Ns_TclGetOpenChannel.3$Z 
    ln $S Ns_TclFile.3$Z Ns_TclGetOpenFd.3$Z 
fi
if test -r Ns_TclInit.3; then
    rm -f Ns_TclInit.3.*
    $ZIP Ns_TclInit.3
    rm -f Ns_TclInitInterps.3 Ns_TclInitInterps.3.* 
    rm -f Ns_TclInitModule.3 Ns_TclInitModule.3.* 
    rm -f Ns_TclInterpServer.3 Ns_TclInterpServer.3.* 
    rm -f Ns_TclLibrary.3 Ns_TclLibrary.3.* 
    ln $S Ns_TclInit.3$Z Ns_TclInitInterps.3$Z 
    ln $S Ns_TclInit.3$Z Ns_TclInitModule.3$Z 
    ln $S Ns_TclInit.3$Z Ns_TclInterpServer.3$Z 
    ln $S Ns_TclInit.3$Z Ns_TclLibrary.3$Z 
fi
if test -r Ns_TclInterp.3; then
    rm -f Ns_TclInterp.3.*
    $ZIP Ns_TclInterp.3
    rm -f Ns_TclAllocateInterp.3 Ns_TclAllocateInterp.3.* 
    rm -f Ns_TclCreateInterp.3 Ns_TclCreateInterp.3.* 
    rm -f Ns_TclDeAllocateInterp.3 Ns_TclDeAllocateInterp.3.* 
    rm -f Ns_TclDestroyInterp.3 Ns_TclDestroyInterp.3.* 
    rm -f Ns_TclEval.3 Ns_TclEval.3.* 
    rm -f Ns_TclMarkForDelete.3 Ns_TclMarkForDelete.3.* 
    ln $S Ns_TclInterp.3$Z Ns_TclAllocateInterp.3$Z 
    ln $S Ns_TclInterp.3$Z Ns_TclCreateInterp.3$Z 
    ln $S Ns_TclInterp.3$Z Ns_TclDeAllocateInterp.3$Z 
    ln $S Ns_TclInterp.3$Z Ns_TclDestroyInterp.3$Z 
    ln $S Ns_TclInterp.3$Z Ns_TclEval.3$Z 
    ln $S Ns_TclInterp.3$Z Ns_TclMarkForDelete.3$Z 
fi
if test -r Ns_TclRegister.3; then
    rm -f Ns_TclRegister.3.*
    $ZIP Ns_TclRegister.3
    rm -f Ns_TclRegisterAtCleanup.3 Ns_TclRegisterAtCleanup.3.* 
    rm -f Ns_TclRegisterAtCreate.3 Ns_TclRegisterAtCreate.3.* 
    rm -f Ns_TclRegisterAtDelete.3 Ns_TclRegisterAtDelete.3.* 
    rm -f Ns_TclRegisterDeferred.3 Ns_TclRegisterDeferred.3.* 
    ln $S Ns_TclRegister.3$Z Ns_TclRegisterAtCleanup.3$Z 
    ln $S Ns_TclRegister.3$Z Ns_TclRegisterAtCreate.3$Z 
    ln $S Ns_TclRegister.3$Z Ns_TclRegisterAtDelete.3$Z 
    ln $S Ns_TclRegister.3$Z Ns_TclRegisterDeferred.3$Z 
fi
if test -r Ns_TclSet.3; then
    rm -f Ns_TclSet.3.*
    $ZIP Ns_TclSet.3
    rm -f Ns_TclEnterSet.3 Ns_TclEnterSet.3.* 
    rm -f Ns_TclFreeSet.3 Ns_TclFreeSet.3.* 
    rm -f Ns_TclGetSet.3 Ns_TclGetSet.3.* 
    rm -f Ns_TclGetSet2.3 Ns_TclGetSet2.3.* 
    ln $S Ns_TclSet.3$Z Ns_TclEnterSet.3$Z 
    ln $S Ns_TclSet.3$Z Ns_TclFreeSet.3$Z 
    ln $S Ns_TclSet.3$Z Ns_TclGetSet.3$Z 
    ln $S Ns_TclSet.3$Z Ns_TclGetSet2.3$Z 
fi
if test -r Ns_TclThread.3; then
    rm -f Ns_TclThread.3.*
    $ZIP Ns_TclThread.3
    rm -f Ns_TclDetachedThread.3 Ns_TclDetachedThread.3.* 
    ln $S Ns_TclThread.3$Z Ns_TclDetachedThread.3$Z 
fi
if test -r Ns_TclTimeObj.3; then
    rm -f Ns_TclTimeObj.3.*
    $ZIP Ns_TclTimeObj.3
    rm -f Ns_TclGetTimeFromObj.3 Ns_TclGetTimeFromObj.3.* 
    rm -f Ns_TclSetTimeObj.3 Ns_TclSetTimeObj.3.* 
    ln $S Ns_TclTimeObj.3$Z Ns_TclGetTimeFromObj.3$Z 
    ln $S Ns_TclTimeObj.3$Z Ns_TclSetTimeObj.3$Z 
fi
if test -r Ns_TempFile.3; then
    rm -f Ns_TempFile.3.*
    $ZIP Ns_TempFile.3
    rm -f Ns_GetTemp.3 Ns_GetTemp.3.* 
    rm -f Ns_ReleaseTemp.3 Ns_ReleaseTemp.3.* 
    ln $S Ns_TempFile.3$Z Ns_GetTemp.3$Z 
    ln $S Ns_TempFile.3$Z Ns_ReleaseTemp.3$Z 
fi
if test -r Ns_Thread.3; then
    rm -f Ns_Thread.3.*
    $ZIP Ns_Thread.3
    rm -f Ns_ThreadCreate.3 Ns_ThreadCreate.3.* 
    rm -f Ns_ThreadExit.3 Ns_ThreadExit.3.* 
    rm -f Ns_ThreadGetName.3 Ns_ThreadGetName.3.* 
    rm -f Ns_ThreadGetParent.3 Ns_ThreadGetParent.3.* 
    rm -f Ns_ThreadId.3 Ns_ThreadId.3.* 
    rm -f Ns_ThreadJoin.3 Ns_ThreadJoin.3.* 
    rm -f Ns_ThreadList.3 Ns_ThreadList.3.* 
    rm -f Ns_ThreadSelf.3 Ns_ThreadSelf.3.* 
    rm -f Ns_ThreadSetName.3 Ns_ThreadSetName.3.* 
    rm -f Ns_ThreadStackSize.3 Ns_ThreadStackSize.3.* 
    rm -f Ns_ThreadYield.3 Ns_ThreadYield.3.* 
    ln $S Ns_Thread.3$Z Ns_ThreadCreate.3$Z 
    ln $S Ns_Thread.3$Z Ns_ThreadExit.3$Z 
    ln $S Ns_Thread.3$Z Ns_ThreadGetName.3$Z 
    ln $S Ns_Thread.3$Z Ns_ThreadGetParent.3$Z 
    ln $S Ns_Thread.3$Z Ns_ThreadId.3$Z 
    ln $S Ns_Thread.3$Z Ns_ThreadJoin.3$Z 
    ln $S Ns_Thread.3$Z Ns_ThreadList.3$Z 
    ln $S Ns_Thread.3$Z Ns_ThreadSelf.3$Z 
    ln $S Ns_Thread.3$Z Ns_ThreadSetName.3$Z 
    ln $S Ns_Thread.3$Z Ns_ThreadStackSize.3$Z 
    ln $S Ns_Thread.3$Z Ns_ThreadYield.3$Z 
fi
if test -r Ns_Thread2.3; then
    rm -f Ns_Thread2.3.*
    $ZIP Ns_Thread2.3
    rm -f Ns_AbsTimedWaitForEvent.3 Ns_AbsTimedWaitForEvent.3.* 
    rm -f Ns_AllocThreadLocalStorage.3 Ns_AllocThreadLocalStorage.3.* 
    rm -f Ns_BeginDetachedThread.3 Ns_BeginDetachedThread.3.* 
    rm -f Ns_BeginThread.3 Ns_BeginThread.3.* 
    rm -f Ns_BroadcastEvent.3 Ns_BroadcastEvent.3.* 
    rm -f Ns_DestroyCriticalSection.3 Ns_DestroyCriticalSection.3.* 
    rm -f Ns_DestroyEvent.3 Ns_DestroyEvent.3.* 
    rm -f Ns_DestroyMutex.3 Ns_DestroyMutex.3.* 
    rm -f Ns_DestroyRWLock.3 Ns_DestroyRWLock.3.* 
    rm -f Ns_DestroySemaphore.3 Ns_DestroySemaphore.3.* 
    rm -f Ns_EnterCriticalSection.3 Ns_EnterCriticalSection.3.* 
    rm -f Ns_ExitThread.3 Ns_ExitThread.3.* 
    rm -f Ns_GetThread.3 Ns_GetThread.3.* 
    rm -f Ns_GetThreadId.3 Ns_GetThreadId.3.* 
    rm -f Ns_GetThreadLocalStorage.3 Ns_GetThreadLocalStorage.3.* 
    rm -f Ns_GetThreadServer.3 Ns_GetThreadServer.3.* 
    rm -f Ns_InitializeCriticalSection.3 Ns_InitializeCriticalSection.3.* 
    rm -f Ns_InitializeEvent.3 Ns_InitializeEvent.3.* 
    rm -f Ns_InitializeMutex.3 Ns_InitializeMutex.3.* 
    rm -f Ns_InitializeRWLock.3 Ns_InitializeRWLock.3.* 
    rm -f Ns_InitializeSemaphore.3 Ns_InitializeSemaphore.3.* 
    rm -f Ns_LeaveCriticalSection.3 Ns_LeaveCriticalSection.3.* 
    rm -f Ns_LockMutex.3 Ns_LockMutex.3.* 
    rm -f Ns_ReadLockRWLock.3 Ns_ReadLockRWLock.3.* 
    rm -f Ns_ReadUnlockRWLock.3 Ns_ReadUnlockRWLock.3.* 
    rm -f Ns_ReleaseSemaphore.3 Ns_ReleaseSemaphore.3.* 
    rm -f Ns_SetEvent.3 Ns_SetEvent.3.* 
    rm -f Ns_SetThreadLocalStorage.3 Ns_SetThreadLocalStorage.3.* 
    rm -f Ns_SetThreadServer.3 Ns_SetThreadServer.3.* 
    rm -f Ns_TimedWaitForEvent.3 Ns_TimedWaitForEvent.3.* 
    rm -f Ns_UTimedWaitForEvent.3 Ns_UTimedWaitForEvent.3.* 
    rm -f Ns_UnlockMutex.3 Ns_UnlockMutex.3.* 
    rm -f Ns_WaitForEvent.3 Ns_WaitForEvent.3.* 
    rm -f Ns_WaitForSemaphore.3 Ns_WaitForSemaphore.3.* 
    rm -f Ns_WaitForThread.3 Ns_WaitForThread.3.* 
    rm -f Ns_WaitThread.3 Ns_WaitThread.3.* 
    rm -f Ns_WriteLockRWLock.3 Ns_WriteLockRWLock.3.* 
    rm -f Ns_WriteUnlockRWLock.3 Ns_WriteUnlockRWLock.3.* 
    ln $S Ns_Thread2.3$Z Ns_AbsTimedWaitForEvent.3$Z 
    ln $S Ns_Thread2.3$Z Ns_AllocThreadLocalStorage.3$Z 
    ln $S Ns_Thread2.3$Z Ns_BeginDetachedThread.3$Z 
    ln $S Ns_Thread2.3$Z Ns_BeginThread.3$Z 
    ln $S Ns_Thread2.3$Z Ns_BroadcastEvent.3$Z 
    ln $S Ns_Thread2.3$Z Ns_DestroyCriticalSection.3$Z 
    ln $S Ns_Thread2.3$Z Ns_DestroyEvent.3$Z 
    ln $S Ns_Thread2.3$Z Ns_DestroyMutex.3$Z 
    ln $S Ns_Thread2.3$Z Ns_DestroyRWLock.3$Z 
    ln $S Ns_Thread2.3$Z Ns_DestroySemaphore.3$Z 
    ln $S Ns_Thread2.3$Z Ns_EnterCriticalSection.3$Z 
    ln $S Ns_Thread2.3$Z Ns_ExitThread.3$Z 
    ln $S Ns_Thread2.3$Z Ns_GetThread.3$Z 
    ln $S Ns_Thread2.3$Z Ns_GetThreadId.3$Z 
    ln $S Ns_Thread2.3$Z Ns_GetThreadLocalStorage.3$Z 
    ln $S Ns_Thread2.3$Z Ns_GetThreadServer.3$Z 
    ln $S Ns_Thread2.3$Z Ns_InitializeCriticalSection.3$Z 
    ln $S Ns_Thread2.3$Z Ns_InitializeEvent.3$Z 
    ln $S Ns_Thread2.3$Z Ns_InitializeMutex.3$Z 
    ln $S Ns_Thread2.3$Z Ns_InitializeRWLock.3$Z 
    ln $S Ns_Thread2.3$Z Ns_InitializeSemaphore.3$Z 
    ln $S Ns_Thread2.3$Z Ns_LeaveCriticalSection.3$Z 
    ln $S Ns_Thread2.3$Z Ns_LockMutex.3$Z 
    ln $S Ns_Thread2.3$Z Ns_ReadLockRWLock.3$Z 
    ln $S Ns_Thread2.3$Z Ns_ReadUnlockRWLock.3$Z 
    ln $S Ns_Thread2.3$Z Ns_ReleaseSemaphore.3$Z 
    ln $S Ns_Thread2.3$Z Ns_SetEvent.3$Z 
    ln $S Ns_Thread2.3$Z Ns_SetThreadLocalStorage.3$Z 
    ln $S Ns_Thread2.3$Z Ns_SetThreadServer.3$Z 
    ln $S Ns_Thread2.3$Z Ns_TimedWaitForEvent.3$Z 
    ln $S Ns_Thread2.3$Z Ns_UTimedWaitForEvent.3$Z 
    ln $S Ns_Thread2.3$Z Ns_UnlockMutex.3$Z 
    ln $S Ns_Thread2.3$Z Ns_WaitForEvent.3$Z 
    ln $S Ns_Thread2.3$Z Ns_WaitForSemaphore.3$Z 
    ln $S Ns_Thread2.3$Z Ns_WaitForThread.3$Z 
    ln $S Ns_Thread2.3$Z Ns_WaitThread.3$Z 
    ln $S Ns_Thread2.3$Z Ns_WriteLockRWLock.3$Z 
    ln $S Ns_Thread2.3$Z Ns_WriteUnlockRWLock.3$Z 
fi
if test -r Ns_ThreadAlloc.3; then
    rm -f Ns_ThreadAlloc.3.*
    $ZIP Ns_ThreadAlloc.3
    rm -f Ns_ThreadCalloc.3 Ns_ThreadCalloc.3.* 
    rm -f Ns_ThreadFree.3 Ns_ThreadFree.3.* 
    rm -f Ns_ThreadMalloc.3 Ns_ThreadMalloc.3.* 
    rm -f Ns_ThreadPool.3 Ns_ThreadPool.3.* 
    rm -f Ns_ThreadRealloc.3 Ns_ThreadRealloc.3.* 
    rm -f Ns_ThreadStrCopy.3 Ns_ThreadStrCopy.3.* 
    rm -f Ns_ThreadStrDup.3 Ns_ThreadStrDup.3.* 
    ln $S Ns_ThreadAlloc.3$Z Ns_ThreadCalloc.3$Z 
    ln $S Ns_ThreadAlloc.3$Z Ns_ThreadFree.3$Z 
    ln $S Ns_ThreadAlloc.3$Z Ns_ThreadMalloc.3$Z 
    ln $S Ns_ThreadAlloc.3$Z Ns_ThreadPool.3$Z 
    ln $S Ns_ThreadAlloc.3$Z Ns_ThreadRealloc.3$Z 
    ln $S Ns_ThreadAlloc.3$Z Ns_ThreadStrCopy.3$Z 
    ln $S Ns_ThreadAlloc.3$Z Ns_ThreadStrDup.3$Z 
fi
if test -r Ns_Time.3; then
    rm -f Ns_Time.3.*
    $ZIP Ns_Time.3
    rm -f Ns_AdjTime.3 Ns_AdjTime.3.* 
    rm -f Ns_DiffTime.3 Ns_DiffTime.3.* 
    rm -f Ns_GetTime.3 Ns_GetTime.3.* 
    rm -f Ns_IncrTime.3 Ns_IncrTime.3.* 
    ln $S Ns_Time.3$Z Ns_AdjTime.3$Z 
    ln $S Ns_Time.3$Z Ns_DiffTime.3$Z 
    ln $S Ns_Time.3$Z Ns_GetTime.3$Z 
    ln $S Ns_Time.3$Z Ns_IncrTime.3$Z 
fi
if test -r Ns_Tls.3; then
    rm -f Ns_Tls.3.*
    $ZIP Ns_Tls.3
    rm -f Ns_TlsAlloc.3 Ns_TlsAlloc.3.* 
    rm -f Ns_TlsGet.3 Ns_TlsGet.3.* 
    rm -f Ns_TlsSet.3 Ns_TlsSet.3.* 
    ln $S Ns_Tls.3$Z Ns_TlsAlloc.3$Z 
    ln $S Ns_Tls.3$Z Ns_TlsGet.3$Z 
    ln $S Ns_Tls.3$Z Ns_TlsSet.3$Z 
fi
if test -r Ns_Uid.3; then
    rm -f Ns_Uid.3.*
    $ZIP Ns_Uid.3
    rm -f Ns_GetGid.3 Ns_GetGid.3.* 
    rm -f Ns_GetUid.3 Ns_GetUid.3.* 
    rm -f Ns_GetUserGid.3 Ns_GetUserGid.3.* 
    rm -f Ns_GetUserHome.3 Ns_GetUserHome.3.* 
    ln $S Ns_Uid.3$Z Ns_GetGid.3$Z 
    ln $S Ns_Uid.3$Z Ns_GetUid.3$Z 
    ln $S Ns_Uid.3$Z Ns_GetUserGid.3$Z 
    ln $S Ns_Uid.3$Z Ns_GetUserHome.3$Z 
fi
if test -r Ns_Url.3; then
    rm -f Ns_Url.3.*
    $ZIP Ns_Url.3
    rm -f Ns_AbsoluteUrl.3 Ns_AbsoluteUrl.3.* 
    rm -f Ns_ParseUrl.3 Ns_ParseUrl.3.* 
    rm -f Ns_RelativeUrl.3 Ns_RelativeUrl.3.* 
    rm -f Ns_SkipUrl.3 Ns_SkipUrl.3.* 
    ln $S Ns_Url.3$Z Ns_AbsoluteUrl.3$Z 
    ln $S Ns_Url.3$Z Ns_ParseUrl.3$Z 
    ln $S Ns_Url.3$Z Ns_RelativeUrl.3$Z 
    ln $S Ns_Url.3$Z Ns_SkipUrl.3$Z 
fi
if test -r Ns_UrlEncode.3; then
    rm -f Ns_UrlEncode.3.*
    $ZIP Ns_UrlEncode.3
    rm -f Ns_DecodeUrl.3 Ns_DecodeUrl.3.* 
    rm -f Ns_EncodeUrl.3 Ns_EncodeUrl.3.* 
    ln $S Ns_UrlEncode.3$Z Ns_DecodeUrl.3$Z 
    ln $S Ns_UrlEncode.3$Z Ns_EncodeUrl.3$Z 
fi
if test -r Ns_UrlSpecific.3; then
    rm -f Ns_UrlSpecific.3.*
    $ZIP Ns_UrlSpecific.3
    rm -f Ns_UrlSpecificAlloc.3 Ns_UrlSpecificAlloc.3.* 
    rm -f Ns_UrlSpecificDestroy.3 Ns_UrlSpecificDestroy.3.* 
    rm -f Ns_UrlSpecificGet.3 Ns_UrlSpecificGet.3.* 
    rm -f Ns_UrlSpecificGetExact.3 Ns_UrlSpecificGetExact.3.* 
    rm -f Ns_UrlSpecificGetFast.3 Ns_UrlSpecificGetFast.3.* 
    rm -f Ns_UrlSpecificSet.3 Ns_UrlSpecificSet.3.* 
    ln $S Ns_UrlSpecific.3$Z Ns_UrlSpecificAlloc.3$Z 
    ln $S Ns_UrlSpecific.3$Z Ns_UrlSpecificDestroy.3$Z 
    ln $S Ns_UrlSpecific.3$Z Ns_UrlSpecificGet.3$Z 
    ln $S Ns_UrlSpecific.3$Z Ns_UrlSpecificGetExact.3$Z 
    ln $S Ns_UrlSpecific.3$Z Ns_UrlSpecificGetFast.3$Z 
    ln $S Ns_UrlSpecific.3$Z Ns_UrlSpecificSet.3$Z 
fi
if test -r Ns_UrlToFile.3; then
    rm -f Ns_UrlToFile.3.*
    $ZIP Ns_UrlToFile.3
    rm -f Ns_SetUrlToFileProc.3 Ns_SetUrlToFileProc.3.* 
    rm -f Ns_UrlIsDir.3 Ns_UrlIsDir.3.* 
    rm -f Ns_UrlIsFile.3 Ns_UrlIsFile.3.* 
    ln $S Ns_UrlToFile.3$Z Ns_SetUrlToFileProc.3$Z 
    ln $S Ns_UrlToFile.3$Z Ns_UrlIsDir.3$Z 
    ln $S Ns_UrlToFile.3$Z Ns_UrlIsFile.3$Z 
fi
exit 0
