
'\"
'\" The contents of this file are subject to the AOLserver Public License
'\" Version 1.1 (the "License"); you may not use this file except in
'\" compliance with the License. You may obtain a copy of the License at
'\" http://aolserver.com/.
'\"
'\" Software distributed under the License is distributed on an "AS IS"
'\" basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
'\" the License for the specific language governing rights and limitations
'\" under the License.
'\"
'\" The Original Code is AOLserver Code and related documentation
'\" distributed by AOL.
'\" 
'\" The Initial Developer of the Original Code is America Online,
'\" Inc. Portions created by AOL are Copyright (C) 1999 America Online,
'\" Inc. All Rights Reserved.
'\"
'\" Alternatively, the contents of this file may be used under the terms
'\" of the GNU General Public License (the "GPL"), in which case the
'\" provisions of GPL are applicable instead of those above.  If you wish
'\" to allow use of your version of this file only under the terms of the
'\" GPL and not to allow others to use your version of this file under the
'\" License, indicate your decision by deleting the provisions above and
'\" replace them with the notice and other provisions required by the GPL.
'\" If you do not delete the provisions above, a recipient may use your
'\" version of this file under either the License or the GPL.
'\" 
'\"
'\" $Header: /Users/dossy/Desktop/cvs/aolserver/doc/Ns_Cache.3,v 1.6 2003/05/31 20:42:41 vasiljevic Exp $
'\"
'\" 
.so man.macros

.TH Ns_Cache 3 4.0 AOLserver "AOLserver Library Procedures"
.BS
'\" Note:  do not modify the .SH NAME line immediately below!
.SH NAME
Ns_CacheBroadcast, Ns_CacheCreate, Ns_CacheCreateEntry, Ns_CacheCreateSz, Ns_CacheDeleteEntry, Ns_CacheDestroy, Ns_CacheFind, Ns_CacheFindEntry, Ns_CacheFirstEntry, Ns_CacheFlush, Ns_CacheFlushEntry, Ns_CacheFree, Ns_CacheGetValue, Ns_CacheKey, Ns_CacheLock, Ns_CacheTryLock, Ns_CacheMalloc, Ns_CacheName, Ns_CacheNextEntry, Ns_CacheSetValue, Ns_CacheSetValueSz, Ns_CacheSignal, Ns_CacheTimedWait, Ns_CacheUnlock, Ns_CacheUnsetValue, Ns_CacheWait \- library procedures
.SH SYNOPSIS
.nf
\fB#include "ns.h"\fR
.sp
\fBNs_CacheBroadcast\fR(\fIarg, arg\fR)
.sp
\fBNs_CacheCreate\fR(\fIarg, arg\fR)
.sp
\fBNs_CacheCreateEntry\fR(\fIarg, arg\fR)
.sp
\fBNs_CacheCreateSz\fR(\fIarg, arg\fR)
.sp
\fBNs_CacheDeleteEntry\fR(\fIarg, arg\fR)
.sp
\fBNs_CacheDestroy\fR(\fIarg, arg\fR)
.sp
\fBNs_CacheFind\fR(\fIarg, arg\fR)
.sp
\fBNs_CacheFindEntry\fR(\fIarg, arg\fR)
.sp
\fBNs_CacheFirstEntry\fR(\fIarg, arg\fR)
.sp
\fBNs_CacheFlush\fR(\fIarg, arg\fR)
.sp
\fBNs_CacheFlushEntry\fR(\fIarg, arg\fR)
.sp
\fBNs_CacheFree\fR(\fIarg, arg\fR)
.sp
\fBNs_CacheGetValue\fR(\fIarg, arg\fR)
.sp
\fBNs_CacheKey\fR(\fIarg, arg\fR)
.sp
\fBNs_CacheLock\fR(\fIarg, arg\fR)
.sp
\fBNs_CacheTryLock\fR(\fIarg, arg\fR)
.sp
\fBNs_CacheMalloc\fR(\fIarg, arg\fR)
.sp
\fBNs_CacheName\fR(\fIarg, arg\fR)
.sp
\fBNs_CacheNextEntry\fR(\fIarg, arg\fR)
.sp
\fBNs_CacheSetValue\fR(\fIarg, arg\fR)
.sp
\fBNs_CacheSetValueSz\fR(\fIarg, arg\fR)
.sp
\fBNs_CacheSignal\fR(\fIarg, arg\fR)
.sp
\fBNs_CacheTimedWait\fR(\fIarg, arg\fR)
.sp
\fBNs_CacheUnlock\fR(\fIarg, arg\fR)
.sp
\fBNs_CacheUnsetValue\fR(\fIarg, arg\fR)
.sp
\fBNs_CacheWait\fR(\fIarg, arg\fR)
.BE

.SH DESCRIPTION
.PP
These functions ...

.SH "SEE ALSO"
nsd(1), info(n)

.SH KEYWORDS

