
'\"
'\" The contents of this file are subject to the AOLserver Public License
'\" Version 1.1 (the "License"); you may not use this file except in
'\" compliance with the License. You may obtain a copy of the License at
'\" http://aolserver.com/.
'\"
'\" Software distributed under the License is distributed on an "AS IS"
'\" basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
'\" the License for the specific language governing rights and limitations
'\" under the License.
'\"
'\" The Original Code is AOLserver Code and related documentation
'\" distributed by AOL.
'\" 
'\" The Initial Developer of the Original Code is America Online,
'\" Inc. Portions created by AOL are Copyright (C) 1999 America Online,
'\" Inc. All Rights Reserved.
'\"
'\" Alternatively, the contents of this file may be used under the terms
'\" of the GNU General Public License (the "GPL"), in which case the
'\" provisions of GPL are applicable instead of those above.  If you wish
'\" to allow use of your version of this file only under the terms of the
'\" GPL and not to allow others to use your version of this file under the
'\" License, indicate your decision by deleting the provisions above and
'\" replace them with the notice and other provisions required by the GPL.
'\" If you do not delete the provisions above, a recipient may use your
'\" version of this file under either the License or the GPL.
'\" 
'\"
'\" $Header: /Users/dossy/Desktop/cvs/aolserver/doc/Ns_ConnDriver.3,v 1.6 2006/04/19 17:37:30 jgdavidson Exp $
'\"
'\" 
.so man.macros

.TH Ns_ConnDriver 3 4.0 AOLserver "AOLserver Library Procedures"
.BS
'\" Note:  do not modify the .SH NAME line immediately below!
.SH NAME
Ns_ConnDriverContext, Ns_ConnDriverName \- Routines to access communication driver data
.SH SYNOPSIS
.nf
\fB#include "ns.h"\fR
.sp
void *
\fBNs_ConnDriverContext\fR(\fIconn\fR)
.sp
char *
\fBNs_ConnDriverName\fR(\fIconn\fR)
.SH ARGUMENTS
.AS Ns_Conn conn in
.AP Ns_Conn conn in
Pointer to open connection.
.BE

.SH DESCRIPTION
.PP
These functions provide access to the underyling communications
driver data for an open connection.

.TP
char *\fBNs_ConnDriverName\fR(\fIconn\fR)
Returns the string name of the communication driver, e.g., "nssock".
This is the name passed in the \fINs_DriverInitData\fR structure
in a call to \fBNs_DriverInit\fR, not the module name for the
particular instance of the loaded driver.

.TP
void *\fBNs_ConnDriverContent\fR(\fIconn\fR)
Returns a pointer to the connection-specific driver context for the
given connection.  This value is that of the \fIarg\fR element of
the underlying \fINs_Sock\fR structure allocated by the server and
used by communication drivers to manage private state.  If the
connection is closed, the value returned is always NULL.

.SH "SEE ALSO"
Ns_DriverInit(3)

.SH KEYWORDS
connection, context
