
'\"
'\" The contents of this file are subject to the AOLserver Public License
'\" Version 1.1 (the "License"); you may not use this file except in
'\" compliance with the License. You may obtain a copy of the License at
'\" http://aolserver.com/.
'\"
'\" Software distributed under the License is distributed on an "AS IS"
'\" basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
'\" the License for the specific language governing rights and limitations
'\" under the License.
'\"
'\" The Original Code is AOLserver Code and related documentation
'\" distributed by AOL.
'\" 
'\" The Initial Developer of the Original Code is America Online,
'\" Inc. Portions created by AOL are Copyright (C) 1999 America Online,
'\" Inc. All Rights Reserved.
'\"
'\" Alternatively, the contents of this file may be used under the terms
'\" of the GNU General Public License (the "GPL"), in which case the
'\" provisions of GPL are applicable instead of those above.  If you wish
'\" to allow use of your version of this file only under the terms of the
'\" GPL and not to allow others to use your version of this file under the
'\" License, indicate your decision by deleting the provisions above and
'\" replace them with the notice and other provisions required by the GPL.
'\" If you do not delete the provisions above, a recipient may use your
'\" version of this file under either the License or the GPL.
'\" 
'\"
'\" $Header: /Users/dossy/Desktop/cvs/aolserver/doc/Ns_Location.3,v 1.5 2003/04/10 22:00:45 shmooved Exp $
'\"
'\" 
.so man.macros

.TH Ns_Location 3 4.0 AOLserver "AOLserver Library Procedures"
.BS
'\" Note:  do not modify the .SH NAME line immediately below!
.SH NAME
Ns_SetConnLocationProc, Ns_SetLocationProc \- Set the location procedure to use
.SH SYNOPSIS
.nf
\fB#include "ns.h"\fR
.sp
void
\fBNs_SetConnLocationProc\fR(\fINs_LocationProc *procPtr\fR)
.sp
void
\fBNs_SetLocationProc\fR(\fIchar *ignored, Ns_LocationProc *procPtr\fR)
.BE

.SH DESCRIPTION
.PP

These functions set the procedure to run when a call to
\fBNs_ConnLocation\fR is made. The location is defined in the form
METHOD://HOSTNAME:PORT, e.g. http://myhost.com:8443.

Setting the location procedure with these functions will cause all
calls to \fBNs_ConnLocation\fR to use the location procedure you
define instead of using the location procedure callback in the
communication module for the connection.

There may be cases where you want to do this. For example, you could
create a location procedure that reports on the values returned by
communication module location procedure callbacks. At the end of that
procedure, you could then return that value after logging the
information making your location procedure is effectively transparent
to the server and other modules.

.TP
\fBNs_SetConnLocationProc\fR(\fIprocPtr\fR)

Set the function to use when \fBNs_ConnLocation\fR is called. This
function is deprecated. Use \fBNs_SetLocationProc\fR instead.
.TP
\fBNs_SetLocationProc\fR(\fIignored, procPtr\fR)

Set the function to use when \fBNs_ConnLocation\fR is called. The
\fIignored\fR argument is reserved for future use.
.SH "SEE ALSO"
nsd(1), info(n), Ns_ConnLocation(3)

.SH KEYWORDS

