
'\"
'\" The contents of this file are subject to the AOLserver Public License
'\" Version 1.1 (the "License"); you may not use this file except in
'\" compliance with the License. You may obtain a copy of the License at
'\" http://aolserver.com/.
'\"
'\" Software distributed under the License is distributed on an "AS IS"
'\" basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
'\" the License for the specific language governing rights and limitations
'\" under the License.
'\"
'\" The Original Code is AOLserver Code and related documentation
'\" distributed by AOL.
'\" 
'\" The Initial Developer of the Original Code is America Online,
'\" Inc. Portions created by AOL are Copyright (C) 1999 America Online,
'\" Inc. All Rights Reserved.
'\"
'\" Alternatively, the contents of this file may be used under the terms
'\" of the GNU General Public License (the "GPL"), in which case the
'\" provisions of GPL are applicable instead of those above.  If you wish
'\" to allow use of your version of this file only under the terms of the
'\" GPL and not to allow others to use your version of this file under the
'\" License, indicate your decision by deleting the provisions above and
'\" replace them with the notice and other provisions required by the GPL.
'\" If you do not delete the provisions above, a recipient may use your
'\" version of this file under either the License or the GPL.
'\" 
'\"
'\" $Header: /Users/dossy/Desktop/cvs/aolserver/doc/Ns_ThreadAlloc.3,v 1.5 2003/04/10 22:01:04 shmooved Exp $
'\"
'\" 
.so man.macros

.TH Ns_ThreadAlloc 3 4.0 AOLserver "AOLserver Library Procedures"
.BS
'\" Note:  do not modify the .SH NAME line immediately below!
.SH NAME
Ns_ThreadAlloc, Ns_ThreadCalloc, Ns_ThreadFree, Ns_ThreadMalloc, Ns_ThreadPool, Ns_ThreadRealloc, Ns_ThreadStrCopy, Ns_ThreadStrDup \- Memory allocation functions for threads (deprecated)
.SH SYNOPSIS
.nf
\fB#include "ns.h"\fR
.sp
void *
\fBNs_ThreadAlloc\fR(\fIsize_t size\fR)
.sp
void *
\fBNs_ThreadCalloc\fR(\fIsize_t nelem, size_t elsize\fR)
.sp
void
\fBNs_ThreadFree\fR(\fIvoid *ptr\fR)
.sp
void *
\fBNs_ThreadMalloc\fR(\fIsize_t size\fR)
.sp
Ns_Pool *
\fBNs_ThreadPool\fR(\fIvoid\fR)
.sp
void *
\fBNs_ThreadRealloc\fR(\fIvoid *ptr, size_t size\fR)
.sp
char *
\fBNs_ThreadStrCopy\fR(\fIchar *str\fR)
.sp
char *
\fBNs_ThreadStrDup\fR(\fIchar *str\fR)
.BE

.SH DESCRIPTION
.PP
These functions are deprecated and are actually wrappers around other functions. You should use the other functions directly.

.TP
\fBNs_ThreadAlloc\fR(\fIsize\fR)

A wrapper for Ns_ThreadMalloc.
.TP
\fBNs_ThreadCalloc\fR(\fInelem, elsize\fR)

A wrapper for ns_calloc.
.TP
\fBNs_ThreadFree\fR(\fIptr\fR)

A wrapper for ns_free.
.TP
\fBNs_ThreadMalloc\fR(\fIsize\fR)

A wrapper for ns_malloc.
.TP
\fBNs_ThreadPool\fR()

Deprecated. Always returns a -1.
.TP
\fBNs_ThreadRealloc\fR(\fIptr, size\fR)

A wrapper for ns_realloc.
.TP
\fBNs_ThreadStrCopy\fR(\fIstr\fR)

A wrapper for ns_strcopy.
.TP
\fBNs_ThreadStrDup\fR(\fIstr\fR)

A wrapper for ns_strdup.
.SH "SEE ALSO"
nsd(1), info(n), ns_calloc(3), ns_malloc(3), ns_realloc(3), ns_free(3), ns_strcopy(3), ns_strdup(3)

.SH KEYWORDS

