#
# Makefile.module --
#
#      This Makefile contains rules for building AOLserver modules.
#      You include this file at the bottom of your module's Makefile.
#
#   Note: We override the LIBS variable because it is not appropriate
#         for most shared objects.
#

ifndef NSHOME
    NSHOME=$(shell pwd)/..
endif

include $(NSHOME)/include/Makefile.global

all: $(MOD)

$(MOD): $(OBJS)
	$(RM) $(MOD)
	$(LDSO) -o $(MOD) $(OBJS) $(MODLIBS)

install: all $(MODINST)
	$(RM) $(INSTBIN)/$(MOD)
	$(CP) $(MOD) $(INSTBIN)

clean:
	$(RM) $(OBJS) $(MOD) so_locations
