<% set dir [nsv_get _ns_stats config.dir] %>

<font size=1>o</font> <a href=<%=$dir%>/cache.adp>Cache</a><br>
<font size=1>o</font> <a href=<%=$dir%>/commands.adp>Commands</a><br>
<font size=1>o</font> <a href=<%=$dir%>/locks.adp>Locks</a><br>
<font size=1>o</font> <a href=<%=$dir%>/log.adp>Log</a><br>
<font size=1>o</font> <a href=<%=$dir%>/mempools.adp>Memory Pools</a><br>
<font size=1>o</font> <a href=<%=$dir%>/process.adp>Process Information</a><br>
<font size=1>o</font> <a href=<%=$dir%>/sched.adp>Scheduled Procedures</a><br>
<font size=1>o</font> <a href=<%=$dir%>/threads.adp>Threads</a><br>
<font size=1>o</font> <a href=<%=$dir%>/url.adp>URL Stats</a><br>
